### ISSUE TITLE
Umlaut error

### ISSUE THREAD

**Issue by WebDesZ** [jrnewell/spotify-ripper#10]
Songs with vowel mutation (umlaut) in the artist name or in the title can note be saved. (äüö,...)
Would be nice if you could fix that.

Example Song
-------------------------------------------------------------------------------
spotify:track:1cvLyT8wV9iMTeZWFDGgUf
Artist: eRRdeKa
Title: Frau <b>für</b> eine Nacht

Logfile
-------------------------------------------------------------------------------
Loading track...
Ripping spotify:track:1cvLyT8wV9iMTeZWFDGgUf
**********/eRRdeKa/Paradies/eRRdeKa - Frau <b>fr</b> eine Nacht.mp3
eRRdeKa - Frau <b>fr</b> eine Nacht.mp3	[ 521.00 Bytes ]

Setting artist: eRRdeKa
Setting album: Paradies
Setting title: Frau <b>für</b> eine Nacht
Setting track info: (9, 12)
Setting disc info: (1, 1)
Setting release year: 2014
Adding image cover.jpg
Time: 00:00	MPEG1, Layer III	[ ~159 kb/s @ 44100 Hz - Joint stereo ]

ID3 v2.4: 7 frames
Writing ID3 version v2.4

Rip complete

Screen
-------------------------------------------------------------------------------
![screen](https://cloud.githubusercontent.com/assets/4548216/7236758/25eb9ca6-e797-11e4-9ad2-f63ac111084f.png)

Thanks
-------------------------------------------------------------------------------
Thank you very much for this project. Keep up the good work (:

**Comment by jrnewell** [comment]
OK.  I think I fixed it in commit f27fa40.  I made unicode the default for file names and paths now and convert to ascii using the ```-a | --ascii``` option.
