### ISSUE TITLE
Option for ID3v2.3 tags

### ISSUE THREAD

**Issue by Madnex** [jrnewell/spotify-ripper#103]
First of all great app! Works like a charm :)

But I'm having a small issue with the tags. Mutagen saves all tags in ID3v2.4 but unfortunately Windows Explorer and some other music players (VLC, Windows Media Player...) can't read that tagging format. Currently I'm converting all files to ID3v2.3 with [Mp3tag](http://www.mp3tag.de/en/).

Is there an option to change the default tagging format?
I noticed that Mutagen supports converting to ID3v2.3 (http://mutagen.readthedocs.org/en/latest/api/id3.html#mutagen.id3.ID3.update_to_v23). Are there any chances you could add an option like that to change the default tagging format?

Thanks in advance!

**Comment by jrnewell** [comment]
ok, i will add this option.

**Comment by Madnex** [comment]
Cool, thanks! I appreciate that :)

**Comment by jrnewell** [comment]
OK. It is added to version ``2.5.0``
