### ISSUE TITLE
TypeError: 'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by nickwong680** [jrnewell/spotify-ripper#106]
Nicks-MacBook-Pro:~ Nick$ spotify-ripper -u 1111111111 -p xxxxx spotify:user:1186814254:playlist:6P6vuQOHi8hCI8RvVPkTIk
Spotify Ripper - v2.5.1
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/Volumes/SP2TB/-=Mp3=-
  Settings directory:	/Users/Nick/.spotify-ripper
  Format String:	{playlist}/{idx:3} - {album_artist} - {album} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Logged in as 1111111111
Loading playlist...
Total Download Size: 5.72 GB
Loading track...
[ 1 / 653 ] Ripping spotify:track:1WByRqqIZ5QY8gYK2zp0TH
/Volumes/SP2TB/-=Mp3=-/600+ Cantopop (Hong Kong)/000 - 吳雨霏 - 座右銘 - 座右銘.mp3
Track Download Size: 9.08 MB
Progress: [================================] 03:58 / 03:58        (~00m 00s remaining)
Total:    [                                ] 03:58 / 42:40:20     (~01d 04h remaining)
Rip complete
000 - 吳雨霏 - 座右銘 - 座右銘.mp3	[ 6.90 MB ]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 279, in run
    set_metadata_tags(args, self.audio_file, track)
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/tags.py", line 74, in set_metadata_tags
    comment = to_ascii(args, args.comment[0], on_error)
TypeError: 'bool' object has no attribute '__getitem__'

**Comment by nickwong680** [comment]
config.ini
[main]
ascii = False
format = {playlist}/{album_artist} - {album} - {track_name}.{ext}
quality = 320
last = True
playlist-m3u = True
playlist-sync = True
comment = True
directory = "/Volumes/SP2TB/-=Mp3=-/"

**Comment by jrnewell** [comment]
The ``comment`` option requires a string (the comment you want to put in like "From Spotify" or whatever) not a boolean.

**Comment by nickwong680** [comment]
Cheers
