### ISSUE TITLE
Unicode Error in option --playlist-m3u

### ISSUE THREAD

**Issue by nholz** [jrnewell/spotify-ripper#107]
Hi!

If I run the ripper with --playlist-m3u it also throws from time to time an unicode conversion error and crashes. At the moment I have no traceback, I'll send that later. 
Also as a feature request, it would be nice if the playlist would not contain full path but relative parts to cwd. 

Cheers

**Comment by jrnewell** [comment]
OK.  Fixed in version ``2.5.2``.
