### ISSUE TITLE
Clipping higher frequencies

### ISSUE THREAD

**Issue by VikasRana** [jrnewell/spotify-ripper#113]
Hello jrnewell,

So far the best thing I have on internet, even better than the best site I browse, for me. Thanks for all your efforts you have put in jrnewell.

I bought one track and downloaded the same from spotify to see the difference. Here is what it looks like,

BOUGHT:-
![bought](https://cloud.githubusercontent.com/assets/5049696/9989680/47ccb382-6078-11e5-8e29-63d3feeaa2f9.png)

FREELY DOWNLOADED:-
![freely obtained](https://cloud.githubusercontent.com/assets/5049696/9989706/86646a9a-6078-11e5-8596-3e6ba14009a9.png)

As you can see the Lower frequencies are good in DOWNLOADED track, but it cuts the higher frequencies where we can see the difference the most. Any way to get spotify-ripper to work on that part effectively?

What I feel is that it may be because trackgain, because the Track Gain of bought one is -11.70 dB and the free one is -11.30 dB. But also I may be not knowing much about it.

**Comment by jrnewell** [comment]
Do you think it is because volume_normalization is turned on?  It doesn't look like track gain is an option that is available to libspotify (and hence spotify-ripper).  Or is this an option available in the encoder program?

**Comment by VikasRana** [comment]
Maybe because of Lame 3.99 that it uses to encode. Lame 3.99 is also not accepted on many webstores. lame 3.98 is the last best known working, maybe Lame 3.99 is not accepted for this reason only. Option to Lame would be nice to test it.
