### ISSUE TITLE
Tagging Featuring artist.

### ISSUE THREAD

**Issue by VikasRana** [jrnewell/spotify-ripper#116]
Would be bad thing to add this in issue, but I don't see any other option but to write here.

I would like this feature to be added jrnewell.

Suppose in spotify track is written as this:

1 TRACK_NAME - ORIGINAL MIX - FEATURING_ARTIST

Would be great if S-R saves track as this,
01. ARTIST_NAME ft FEATURING_ARTIST - TRACK_NAME (ORIGINAL MIX)

This will be a great addition to this lovely program.

Test Song: spotify:track:0XJc618IpG2Z3tyDib6lsT

**Comment by jrnewell** [comment]
so.... if there are multiple artists (x1, x2, x3) it would say "feat. x2, x3 ...."?  Right now it just uses the fist artist for track_artist.

**Comment by VikasRana** [comment]
Yes, like this:

01. main_artist ft artist_1, artist_2 & artist_3 - track_name (original remix) 

Something like that :)

**Comment by jrnewell** [comment]
OK.  I added a new format option ``{feat_artists}`` to version ``2.6.0``.  This is how you use it (it is a bit special compared to the others):

```
Format variable ``feat_artists`` takes a prefix string to be prepended before the output.  For example, ``{feat_artists:featuring} will produce the follow ouputing ``featuing Bruno Mars``.  If there are no featuring artists, the prefix string (and any preceeding spaces) will not be included.
```

**Comment by VikasRana** [comment]
You rock!!!

Thanks again for this.

**Comment by jrnewell** [comment]
what format string are you using?

**Comment by VikasRana** [comment]
Track URI ::  spotify:track:0XJc618IpG2Z3tyDib6lsT 

Format :: {track_num} - {artist} {feat_artists:ft} - {track_name}.{ext}

**Comment by jrnewell** [comment]
Hmm the track name seems to be "One Night Lover - Original Mix".  Any idea how to add a generic option for what you are asking?

**Comment by VikasRana** [comment]
Hey J,

I have absolutely no idea. Sorry. Just have an idea that the last DASH and the SPACE just after that DASH may be replaced with '(' and end every song name with ')'

**Comment by jrnewell** [comment]
Hey, sorry for the delay.  I added ``{track_name:paren}`` to ``2.6.3`` that does what you want.  Let me know if you see any issues.
