### ISSUE TITLE
Can't update pyspotify

### ISSUE THREAD

**Issue by beboeverbebo** [jrnewell/spotify-ripper#117]
I was trying to update spotify-ripper and it failed at pyspotify ,tried updating only pyspotify the same happened ,so any ideas?

<img width="651" alt="captura de ecra 2015-09-26 as 19 48 21" src="https://cloud.githubusercontent.com/assets/12373549/10119237/af5045e2-6487-11e5-833a-f4d94473c9a0.png">

**Comment by jrnewell** [comment]
run with root permissions using ``sudo``

```
sudo pip install spotify-ripper --upgrade
```

**Comment by beboeverbebo** [comment]
thank you once again @jrnewell !!
