### ISSUE TITLE
What if I use Facebook Login instead of regular username and password?

### ISSUE THREAD

**Issue by mabdelfattah** [jrnewell/spotify-ripper#122]
Then, how can I use this tool?

**Comment by garis** [comment]
Facebook login uses the same user name and password that you use on facebook.

**Comment by jrnewell** [comment]
I think that is correct... can you confirm and I will add it to the README

**Comment by garis** [comment]
In my case I have the Facebook login for Spotify and for using this tool I simply entered the Facebook login data (email and the Facebook password).
I also tried to login using my Spotify user number and the complete Facebook name, and they didn't work.

**Comment by mabdelfattah** [comment]
Yeah it worked fine.
