### ISSUE TITLE
Could not create '/Library/Python/2.7/site-packages/pycparser': Permission denied

### ISSUE THREAD

**Issue by ludovico1203** [jrnewell/spotify-ripper#123]
Hi all!
I have a problem when return che command : 
pip install spotify-ripper

After downloading  the various packages, an error comes out  (see below). What I need to do? Thank you!
 
Installing collected packages: pycparser, cffi, pyspotify, colorama, mutagen, requests, schedule, spotify-ripper
  Running setup.py install for pycparser
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/hh/pqf5sg855ls_pr2n3qy0j_d80000gn/T/pip-build-KLvVpk/pycparser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/hh/pqf5sg855ls_pr2n3qy0j_d80000gn/T/pip-2YuLdZ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/pycparser
    copying pycparser/__init__.py -> build/lib/pycparser
    copying pycparser/_ast_gen.py -> build/lib/pycparser
    copying pycparser/_build_tables.py -> build/lib/pycparser
    copying pycparser/ast_transforms.py -> build/lib/pycparser
    copying pycparser/c_ast.py -> build/lib/pycparser
    copying pycparser/c_generator.py -> build/lib/pycparser
    copying pycparser/c_lexer.py -> build/lib/pycparser
    copying pycparser/c_parser.py -> build/lib/pycparser
    copying pycparser/lextab.py -> build/lib/pycparser
    copying pycparser/plyparser.py -> build/lib/pycparser
    copying pycparser/yacctab.py -> build/lib/pycparser
    creating build/lib/pycparser/ply
    copying pycparser/ply/__init__.py -> build/lib/pycparser/ply
    copying pycparser/ply/cpp.py -> build/lib/pycparser/ply
    copying pycparser/ply/ctokens.py -> build/lib/pycparser/ply
    copying pycparser/ply/lex.py -> build/lib/pycparser/ply
    copying pycparser/ply/yacc.py -> build/lib/pycparser/ply
    copying pycparser/_c_ast.cfg -> build/lib/pycparser
    running install_lib
    creating /Library/Python/2.7/site-packages/pycparser
    error: could not create '/Library/Python/2.7/site-packages/pycparser': Permission denied
    
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/hh/pqf5sg855ls_pr2n3qy0j_d80000gn/T/pip-build-KLvVpk/pycparser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/hh/pqf5sg855ls_pr2n3qy0j_d80000gn/T/pip-2YuLdZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/hh/pqf5sg855ls_pr2n3qy0j_d80000gn/T/pip-build-KLvVpk/pycparser
/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by ludovico1203** [comment]
ps : the errore concerning "SSLContext object is not available" is because I didn't install pyenv.
After installing pyenv I still have :
error: could not create '/Library/Python/2.7/site-packages/pycparser': Permission denied

**Comment by jrnewell** [comment]
Try running
```
sudo pip install spotify-ripper
```

**Comment by ludovico1203** [comment]
Hi,
ok now terminal says:

Installing collected packages: pycparser, cffi, pyspotify, colorama, mutagen, requests, schedule, spotify-ripper
  Running setup.py install for pycparser
  Running setup.py install for colorama
  Running setup.py install for mutagen
  Running setup.py install for schedule
  Running setup.py install for spotify-ripper
Successfully installed cffi-1.2.1 colorama-0.3.3 mutagen-1.30 pycparser-2.14 pyspotify-2.0.5 requests-2.8.1 schedule-0.3.2 spotify-ripper-2.6.2


Now I need to execute command : pyenv rehash   ?
Thanks

**Comment by jrnewell** [comment]
Yeah it couldn't hurt.  Then do ``spotify-ripper -h`` to see if it installed properly.

**Comment by ludovico1203** [comment]
Fantastic, now its' working. One last question. I want to change output directory but when I type : spotify-ripper -d /Users/User/Download/Spotifydownload       it says :  spotify-ripper: error: too few arguments.
Also I don't have any config.ini file in the default directory !
Thank you for your help

**Comment by ludovico1203** [comment]
Looking into issues I found a solution for confing.ini, but it seems that output directory is changing everytime, even if I put into config.ini   the command:   directory = /Users/User/Download/Spotifydownload

**Comment by jrnewell** [comment]
You need to include a spotify URI as an argument to tell the script what you want rip (track, playlist, etc...).  You can find the URI by right-clicking on a track or playlist in Spotify desktop app.  See the README for more advanced usage.

**Comment by ludovico1203** [comment]
Hi, I solved it. I didn't uncomment the line  [main]  !  Thank you again your your nice tool!

**Comment by MaxDout** [comment]
Hi :smile:, I'm having a similar problem with the `pip install spotify-ripper` command when following the [Mac OSX instructions](https://github.com/jrnewell/spotify-ripper#mac-os-x). When I run `sudo pip install spotify-ripper` I get:

```
[…]
    byte-compiling /Library/Python/2.7/site-packages/mutagen/oggtheora.py to oggtheora.pyc
    byte-compiling /Library/Python/2.7/site-packages/mutagen/oggvorbis.py to oggvorbis.pyc
    byte-compiling /Library/Python/2.7/site-packages/mutagen/optimfrog.py to optimfrog.pyc
    byte-compiling /Library/Python/2.7/site-packages/mutagen/trueaudio.py to trueaudio.pyc
    byte-compiling /Library/Python/2.7/site-packages/mutagen/wavpack.py to wavpack.pyc
    running install_data
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-5yuWhR/mutagen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9Z_n8d-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-5yuWhR/mutagen
```

I'm then unable to run `pyenv rehash`: `-bash: pyenv: command not found`

**Comment by jrnewell** [comment]
Are you using El Capitan?  ``sudo`` won't work in this case because System Integrity Protection in El Cap prevents you from writing to ``/System/Library/...`` even running as root.

It doesn't look like you have pyenv setup properly since you cannot find the command ``pyenv``.  An easy way to set this up is to use the pyenv-installer
```
$ curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
```

There are alternatives such as installing python using homebrew, using virtualenv, reconfiguring setup_tools to point to a user-controlled directory, or even disabling SIP.  But pyenv is the better way IMO.

**Comment by MaxDout** [comment]
Thank you!

pyenv worked! But unfortunately I'm running El Cap :cry:.

> Are you using El Capitan? sudo won't work in this case because System Integrity Protection in El Cap prevents you from writing to /System/Library/... even running as root.

So does this mean that I'm unable to use spotify-ripper?

**Comment by jrnewell** [comment]
Yeah you can run it on El Cap using pyenv.  Once you have pyenv installed just run the following to install a python runtime:
```
pyenv install 2.7.10
pyenv global 2.7.10
```
Then continue with installing spotify-ripper
```
$ brew install homebrew/binary/libspotify
$ sudo ln -s /usr/local/opt/libspotify/lib/libspotify.12.1.51.dylib \
    /usr/local/opt/libspotify/lib/libspotify
$ brew install lame
$ pip install spotify-ripper
$ pyenv rehash
```

**Comment by MaxDout** [comment]
That did the trick! Thank you so much :zap:
