### ISSUE TITLE
Script doesn't stop running in terminal

### ISSUE THREAD

**Issue by 14granville** [jrnewell/spotify-ripper#124]
disclaimer : i'm a complete newbie, it's my first time ever using terminal let alone a python script

I have managed to install the program by following the instructions. It works fine, I succeed when I rip spotify songs except that the script doesn't stop running at the end and gives me the following errors : 

Rip complete
Breakbot Feat. Irfane - Baby I'm Yours.alac.m4a	[ 24.59 MB ]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 290, in run
    set_metadata_tags(args, self.audio_file, track)
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/tags.py", line 331, in set_metadata_tags
    audio = m4a.M4A(audio_file)
  File "/usr/local/lib/python2.7/site-packages/mutagen/_file.py", line 42, in __init__
    self.load(filename, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mutagen/m4a.py", line 87, in load
    raise error("deprecated")
error: deprecated

As I don't know what to do could someone enlighten me ?
maybe an error with mutagen ?

I would like to thank the authors of this program which is really convenient for me as it allows me to listen to my playlists on my ipod shuffle, something I could not do before despite paying spotify premium.

Edit : i'm requesting a standard rip with --alac to get an apple lossless output.

**Comment by MaryCoding** [comment]
I am getting the same error when using option `--mp4`. It hangs in the terminal. It works well with default `mp3`. Can someone bring some insight about this issue?

**Comment by jrnewell** [comment]
Yeah, sorry about that.  It looks like the mutagen interface to m4a is deprecated in mutagen 1.3.1.  I downgrade mutagen for now and I believe that should fix this issue.  Please upgrade spotify-ripper to version ``2.6.2``.

**Comment by 14granville** [comment]
Thanks !

**Comment by jrnewell** [comment]
Let me know if you still see this issue so I can close it.  Thanks!

**Comment by 14granville** [comment]
Everything works for me.
