### ISSUE TITLE
Particular track never starts

### ISSUE THREAD

**Issue by leemmcc** [jrnewell/spotify-ripper#126]
I noticed this track when trying to rip a playlist, but even directly, it never actually starts the transcode and will just hang..

spotify:track:7zpZQzTwWBN0eOsmb4WPH3
Spotify Ripper - v2.6.2
  Encoding output:      MP3, CBR 320 kbps
  Spotify bitrate:      320 kbps
  Unicode support:      Yes
  Output directory:    **
  Settings directory:  **
  Format String:        {playlist}/{artist} - {track}.{ext}
  Overwrite files:      No
Logging in...
Logged in as **
Loading track...
Ripping spotify:track:7zpZQzTwWBN0eOsmb4WPH3
**/No Playlist/Fetty Wap - My Way (feat. Monty).mp3
Track Download Size: 8.13 MB

<no progress bar or anything>

Not sure how to tell what's going on with it or what the error may be.

**Comment by fiyawerx** [comment]
If it helps, I found the same track on another playlist but with another URI that DOES work ok - 
spotify:track:1WoOzgvz6CgH4pX6a1RKGp

 spotify:track:1WoOzgvz6CgH4pX6a1RKGp
Spotify Ripper - v2.6.2
  Encoding output:      MP3, CBR 320 kbps
  Spotify bitrate:      320 kbps
  Unicode support:      Yes
  Output directory:     **
  Settings directory:   **
  Format String:        {playlist}/{artist} - {track}.{ext}
  Overwrite files:      No
Logging in...
Logged in as **
Loading track...
Ripping spotify:track:1WoOzgvz6CgH4pX6a1RKGp
**/No Playlist/Fetty Wap - My Way (feat. Monty).mp3
Track Download Size: 8.13 MB
Progress: [=============                           ] 01:14 / 03:33        (~01m 30s remaining

**Comment by leemmcc** [comment]
Not sure what happened, but I tried it again on the first track that was failing today and it ripped right away. (When it was hanging, it hung for ~15 minutes until I killed it) Closing this issue.
