### ISSUE TITLE
Doesnt understand why it wont work

### ISSUE THREAD

**Issue by RobertoGeuke** [jrnewell/spotify-ripper#128]
I have zero errors when I run  

sudo spotify-ripper -u ******@hotmail.com -p ****** -k spotify_appkey.key spotify:track:57Y3UccJEJqT8w8RWkUAz0

It returns: 

Spotify Ripper - v2.6.2
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/home/roberto/Downloads
  Settings directory:	/home/roberto/.spotify-ripper
  Format String:	{album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:	No

But I cant find the files. What am I doing wrong?

**Comment by theonewhoistwo** [comment]
try to use your username instead of ur email. 

instead of ***@hotmail.com use the username u see in spotify in the top right corner. Do you see a progress bar?

**Comment by jrnewell** [comment]
What does it say after that?   Does it says something like -
```
Logging in...
Logged in as xxxxx
Loading track...
Ripping spotify:track:52xaypL0Kjzk0ngwv3oBPR
/Users/xxxx/Downloads/Spotify/Michael Jackson/HIStory - PAST, PRESENT AND FUTURE - BOOK I/Michael Jackson - Beat It.mp3
Track Download Size: 9.84 MB
Progress: [==                                      ] 00:16 / 04:18        (~01m 20s remaining)
```

According to your settings, the files should be in  /home/roberto/Downloads/<artist>/....

**Comment by RobertoGeuke** [comment]
I dont see anything after I run it except for what I posted in the first post. Changing my email into my spotify user id doesnt help either.

**Comment by jrnewell** [comment]
Does it just immediately exit or hang?  Which platform are you using?

**Comment by theonewhoistwo** [comment]
try to use it without the -p for password. You will get asked for it later on. I had the same problem when i first tried it.

**Comment by jadmanx** [comment]
i get every time 

Logging in...
Password: 
Logged in failed: BAD_USERNAME_OR_PASSWORD
Encountered issue while logging into Spotify, aborting...

but its the right spotify login, the facebook email and password
