### ISSUE TITLE
Spotify URI spotify:album timing out?

### ISSUE THREAD

**Issue by gt9228a** [jrnewell/spotify-ripper#13]
Everything is working perfectly using a Spotify:playlist URI, however the script continues to fail (timeout) when I try to load any spotify:album URI.  

Ex:  spotify:album:2IVZPDXb7LFbyukqaoWpYR is not working?

**Comment by jrnewell** [comment]
That is strange - it timeouts even when I increase the timeout to a few minutes.  It seems to be an upstream bug with pyspotify or libspotify.  However, it still seems to work fine when just loading the album browser, so I made that change in commit 36f5825.  Let me know if that works for you.
