### ISSUE TITLE
Fix Readme: Lossless formats not available on Spotify

### ISSUE THREAD

**Issue by timpulver** [jrnewell/spotify-ripper#130]
Spotify only streams with 320kbps, so ripping to lossless is absolute nonsense.
The readme should make clear, that Spotify does not support this kind of quality and it can only be used to convert other audio files.

**Comment by jrnewell** [comment]
Yes.  It implies that using FLAC is "losses" from the respect that is has already been encoded by Spotify using 320kbps OGG but will not be transcoded further.

If you don't like the wording in the README, feel free to submit a pull request.
