### ISSUE TITLE
m3u playlist are created empty

### ISSUE THREAD

**Issue by feraudet** [jrnewell/spotify-ripper#134]
Hi,

m3u playlist are created empty (empty file)

:~$ spotify-ripper -V
2.6.2

**Comment by feraudet** [comment]
For info : 
pip freeze 
colorama==0.3.3
mutagen==1.30
pyspotify==2.0.5
requests==2.7.0
schedule==0.3.2

**Comment by jrnewell** [comment]
Can you try version ``2.6.5``?

**Comment by feraudet** [comment]
Hi,
Work perfectly with 2.6.5. 
Many thanks
Cyril
