### ISSUE TITLE
detect if other spotify instance is interrupting

### ISSUE THREAD

**Issue by WebDesZ** [jrnewell/spotify-ripper#14]
Hello,

Could you add the feature, that if a song stops recording it automatically exits? Or deletes the file?

Example:

Progress: [====================================    ] 4:17 / 4:42 (Someone starts playing using the same account)
Aborting...
Deleting partially ripped file
Logging out...

**Comment by jrnewell** [comment]
OK, I will do some research into implementing this.  Unfortunately, I am a somewhat limited by what libspotify and pyspotify expose to me and this information might not be available.  Does it disconnect right now if you make multiple connections or does it change the content being streamed?

**Comment by WebDesZ** [comment]
It just stops the script. No further output.

As example:
Progress: [==================================== ] 4:17 / 4:42

**Comment by jrnewell** [comment]
I committed a fix for it in commit 9c8f817 / version ```1.1.1```.
