### ISSUE TITLE
No credentials stored

### ISSUE THREAD

**Issue by lauftorsten** [jrnewell/spotify-ripper#141]
Hi,

I've a problem with the login at Spotify.

Installation works fine. After that I try to test and get this error:

spotify-ripper -u USERNAME spotify:track:52xaypL0Kjzk0ngwv3oBPR
Spotify Ripper - v2.6.8
  Encoding output:      Ogg Vorbis, VBR 10
  Spotify bitrate:      320 kbps
  Unicode support:      ASCII only
  Output directory:     /root
  Settings directory:   /root/.spotify-ripper
  Format String:        {album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:      No
Logging in...
No credentials stored
Encountered issue while logging into Spotify, aborting...

Do you have an idea what's going wrong?

This is a ubuntu server installation. Hope this works?

Torsten

**Comment by jrnewell** [comment]
Do you have a config file set up?  Does it help if you put your username in quotes?  It seems to be triggering the "login as last user" option but you haven't logged in yet...

**Comment by lauftorsten** [comment]
Hi,

my config.ini looks like:
[main]
ascii = True
format = {album_artist}/{album}/{artist} - {track_name}.{ext}
quality = 320
vorbis = true
last = True

Quotes not working :-(

**Comment by jrnewell** [comment]
Yeah you have to remove the "last = True" from your config file until you have logged in once.  I will add something to detect this scenarios to make it more friendly.  Thanks!

**Comment by lauftorsten** [comment]
Yeah great... It works!
Thank you very much...

Torsten
