### ISSUE TITLE
128 kbps audio

### ISSUE THREAD

**Issue by ChajusSaib** [jrnewell/spotify-ripper#143]
For some reason the files I am get are 128 kbps instead of 320. Any ideas?

**Comment by jrnewell** [comment]
Can you post the command-line arguments, config file you are using.  Also the output of the program when it first starts that prints the configuration you are using.

**Comment by ChajusSaib** [comment]
```
spotify-ripper -k /home/user/Documents/spotify_appkey.key -u <user> -p <pass> URI

Spotify Ripper - v2.6.9
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/home/user
  Settings directory:	/home/user/.spotify-ripper
  Format String:	{album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Logged in as <user>
Loading track...

```

**Comment by ChajusSaib** [comment]
Could you try do file <sonename> and see what you get. Thank you

**Comment by jrnewell** [comment]
I think you are fine - it says you are streaming from Spotify at 320 kbps.  Your bitrate of the ripped file might be lower because it uses a more efficient variable bitrate encoding.  If you want a constant 320 kbps, you can use the ``--cbr`` option, but your files will be larger.

**Comment by ChajusSaib** [comment]
Thank you!
