### ISSUE TITLE
spotify-ripper

### ISSUE THREAD

**Issue by jadmanx** [jrnewell/spotify-ripper#147]
i only get if i whant to ripp a song

spotify-ripper: line 3: ?????D?:Q?C?m??p?0?3B???
  ?x???Yu?O?x????~???}O6?b	gi?-?=kr|???K??1?(a?L?6??????Y?x??Ot?k}T{???п????5??7b2?n??L?s?EO?y?????&???k??keOGQk??Ŭ!
ˍ?????1? ??p|?<t???R?+5???R
?Z: command not foundҸ#???x?.?h݆pJl؉?K5?

**Comment by jadmanx** [comment]
if i whant install it again i get 

pip install spotify-ripper
Requirement already satisfied (use --upgrade to upgrade): spotify-ripper in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyspotify==2.0.5 in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.3.3 in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): mutagen==1.30 in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): schedule>=0.3.1 in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.0.0 in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages (from pyspotify==2.0.5->spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): pycparser in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages (from cffi>=1.0.0->pyspotify==2.0.5->spotify-ripper)


i have upgrate to 10.11.3

**Comment by jrnewell** [comment]
Which encoding are you using?  This really only supports utf-8/English.

**Comment by jadmanx** [comment]
i downt know. how can i cange it to utf-8 ?

**Comment by jrnewell** [comment]
Sorry for the slow reply, I was on vacation for the holidays.  Do any of these help?

```shell
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export PYTHONIOENCODING="utf-8"
```
