### ISSUE TITLE
Some tracks stuck half way

### ISSUE THREAD

**Issue by krulkrul** [jrnewell/spotify-ripper#148]
Some tracks are stuck half way during the ripping process while most tracks are fine.

This is one of the tracks that are stuck at 1:29.
spotify-ripper -u xxx --flac -p yyy spotify:track:5ERnPWGQc5QK7M7HW3rjC6

Example:
Track Download Size: 6.41 MB
Progress: [==========          ] 01:29 / 02:48        (~00m 55s remaining)

Using Ubuntu 15.10 / Spotify Ripper - v2.6.2

**Comment by jkuettner** [comment]
Another track is this one at 11:47:

spotify:track:03q4YwuqNWjd5M9WJygz1z

the on_music_delivery function is not triggered anymore so the self.rip_queue is empty and the process hangs...

**Comment by jrnewell** [comment]
Let me look into it... if I cannot fix the fact that streaming stops did you just want it to continue with the next track after a timeout instead of hanging?

**Comment by jkuettner** [comment]
> if I cannot fix the fact that streaming stops did you just want it to continue with the next track after a timeout instead of hanging?

Yes, if this is an upstream error of libspotify it would be nice to skip the corrupted track..

**Comment by krulkrul** [comment]
Agree, thanks.

I have around 3 tracks out of a playlist of 2,500. So it's pretty rare, but better to skip them then let it hung.

**Comment by jrnewell** [comment]
Added a timeout to version ``2.7.0``.

**Comment by krulkrul** [comment]
Validated with version 2.7.0 and timeout works like a charm. Thanks!

Console output for spotify:track:4BS9q82WF5lL8WyWJBFqMe:

```
Progress: [============        ] 03:12 / 05:02        (~01m 40s remaining)
Total:    [                    ] 03:12 / 39:26:15     (~01d 10h remaining)Spotify error detected
Timeout while ripping track
Skipping to next track...
Deleting partially ripped file
```
