### ISSUE TITLE
(suggestion) schedule sleeps during rip operation

### ISSUE THREAD

**Issue by h-rezaei** [jrnewell/spotify-ripper#155]
Hi there

Please excuse me if this is not a right place for  feature suggestions, I'm still new to github.
I have a suggestion that would benefit me personally, But I don't know if It'd be good for others too, so I'm just throwing it in here.

So, My ISP decreases my internet downstream speed if i continuessly download.
I was thinking of two config options that would help solve my problem.  "Sleep after X amount of tracks are downloaded" and "sleep for X minutes".
Then I could set it so if i was downloading 60 tracks, It'd pause after downloading 30 of them for 50 minutes, then return to  downloading and ripping the rest.
I have no technical skills, I'm not sure if this is doable either, I'm putting it here as a wishlist.
Thanks
Cheers

**Comment by jrnewell** [comment]
would it just exit after x minutes and then you later manually rerun it?  I could add that, i don't think it would be too difficult.

**Comment by h-rezaei** [comment]
I was thinking about it exit at X minutes, wait for X minutes then 
return downloading,  and then continue this loop.

**Comment by jrnewell** [comment]
Added this feature to version ``2.7.0`` with options ``--stop-after`` and ``--resume-after``.  So for example if you it to run for 2 hours 30 minutes and then sleep for 4 hours (and repeat) you would pass ``--stop-after "2h30m" --resume-after "4h"``.
