### ISSUE TITLE
Ripping failed - execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by awillinger** [jrnewell/spotify-ripper#156]
I am currently in the process of ripping my playlist with ~460 songs in it.
It works for the bigger part, but 27 of them fail.

Example:

    Loading track...
    [ 33 / 9 ] Ripping spotify:track:2CbuG4ib5Wg5q8AEhVgll7
    /home/user/_rip/DJ Antoine - Ma ChÃ©rie - DJ Antoine vs Mad Mark 2k12 Radio Edit.flac
    Track Download Size: 7.29 MB
    Spotify error detected
    execv() arg 2 must contain only strings
    Skipping to next track...
    Loading track...

I did some tests with the ripper.py, but can't find anything where the program would pass any ints/other types of variables.
Any help would be appreciated.

**Comment by jrnewell** [comment]
can you give the arguments/configuration you are using and the platform it is running on?  It looks like your terminal is having difficultly handling unicode characters?

**Comment by awillinger** [comment]
Command line:

    spotify-ripper -u<user> -p<pass> --flat --flac spotify:user:<userid>:playlist:<playlistid>

Didn't change anything on the config file itself.

Running on Debian 7 64bit with all latest updates, libspotify 12.1.51. It also doesn't only fail with that track, same error occurs with ones without unicode chars (e.g. Pitbull - I Know You Want Me (Calle Ocho))

**Comment by jrnewell** [comment]
Just curious.. are you connecting via PuTTY or just running Debian as a desktop?

**Comment by awillinger** [comment]
Yes, I am using PuTTY to connect (is a VPS)

**Comment by jrnewell** [comment]
I am not sure if this will help, but can you load your profile -> 'Window' -> 'Translation' -> confirm that 'Remote character set' is set to UTF-8 and save profile.

The only other thing I can think of is some argument is still Unicode when calling Popen (maybe the audio_file?).  I will make a change to encode all the arguments to Popen.

**Comment by awillinger** [comment]
It helped somewhat, ripped two more tracks. ~27 still fail though (out of 480).

**Comment by jrnewell** [comment]
I added the unicode encoding to ``2.7.1``. Let me know if that helps at all...

**Comment by awillinger** [comment]
It does, entire playlist ripped successfull now.
