### ISSUE TITLE
Store when a track was added to a playlist?

### ISSUE THREAD

**Issue by danyal** [jrnewell/spotify-ripper#159]
For playlists, would it be possible to add an option that stores when the track was added to the playlist to the comments field (or another suitable tag)?

**Comment by jrnewell** [comment]
Like in the MP3 ID3 comments tag?  And when you say "added", do you mean like when you ripped it locally?

**Comment by danyal** [comment]
Yes, in the ID3 comments tag. By added I meant when it was added to the playlist (according to Spotify). This is really useful info if you want to know when you discovered a track etc.

In pyspotify the information is on the PlaylistTrack object: https://pyspotify.mopidy.com/en/latest/api/playlist/#spotify.PlaylistTrack

**Comment by jrnewell** [comment]
OK.  I added this feature to ``2.7.1``.  In the ``--comment`` option, it will replace the string ``{create_time}`` with the time it was added to the playlist.  It also supports ``{creator}`` since it was also a property in the PlaylistTrack object.

**Comment by jrnewell** [comment]
If you are still using this, the tags have been renamed in version ``2.8.0`` to ``{playlist_track_add_time}`` and ``{playlist_track_add_user}`` to be clearer.
