### ISSUE TITLE
Can't login even if the credential are correct

### ISSUE THREAD

**Issue by ilteoood** [jrnewell/spotify-ripper#160]
<githubroot>Logged in failed: BAD_USERNAME_OR_PASSWORD
Encountered issue while logging into Spotify, aborting...
 Loading playlist...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 199, in run
    tracks = get_tracks_from_uri(uri)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 194, in get_tracks_from_uri
    return self.load_link(uri)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 361, in load_link
    self.current_playlist.load()
AttributeError: 'NoneType' object has no attribute 'load'

My system is a raspberry pi 2, updated to the last version.</githubroot>

**Comment by jrnewell** [comment]
I will investigate this more... you are the third or fourth person to complain about this so something is obviously wrong.  Any users have a workaround?

**Comment by ilteoood** [comment]
I have:
- removed python3-pip using apt-get
- reinstalled it using easy_install
- reinstalled from the ground spotify-ripper
And the attribute error is gone! But still have the login error

**Comment by ilteoood** [comment]
@jrnewell Can, this error message, help you?
"Session must be logged in and online to load objects: ConnectionState.LOGGED_OUT: 0"

**Comment by jrnewell** [comment]
Found this on the Mopidy Spotify github readme - not sure if it will help:
> If you created your account through Facebook you'll need to create a "device password" to be able to use Mopidy-Spotify. Go to http://www.spotify.com/account/set-device-password/, login with your Facebook account, and follow the instructions.
