### ISSUE TITLE
ImportError: /home/kaiser/.local/lib/python2.7/site-packages/_cffi_backend.so: undefined symbol: PyUnicodeUCS4_AsASCIIString

### ISSUE THREAD

**Issue by Candelero** [jrnewell/spotify-ripper#162]
Hello,

I followed the install guide and after some problems I got pyenv installed. The command "$ pip install spotify-ripper" let to the following message:
>You are using pip version 6.1.1, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting spotify-ripper
  Using cached spotify-ripper-2.7.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyspotify==2.0.5 in /home/kaiser/.local/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.3.3 in /home/kaiser/.local/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): mutagen==1.30 in /home/kaiser/.local/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /home/kaiser/.local/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): schedule>=0.3.1 in /home/kaiser/.local/lib/python2.7/site-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.0.0 in /home/kaiser/.local/lib/python2.7/site-packages (from pyspotify==2.0.5->spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /home/kaiser/.local/lib/python2.7/site-packages (from cffi>=1.0.0->pyspotify==2.0.5->spotify-ripper)
Installing collected packages: spotify-ripper
  Running setup.py install for spotify-ripper
Successfully installed spotify-ripper-2.7.1

Is it ok? After there was no ~/.spotify-ripper folder, so I created one and copied the spotify_appkey.key.
But when I try to download a song, I get the following problem:

>$ spotify-ripper -u USERNAME -p PW spotify:track:52xaypL0Kjzk0ngwv3oBPR
Traceback (most recent call last):
  File "/home/kaiser/.pyenv/versions/2.7.10/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.7.1', 'console_scripts', 'spotify-ripper')()
  File "/home/kaiser/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kaiser/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/home/kaiser/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/home/kaiser/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kaiser/.pyenv/versions/2.7.10/bin/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/home/kaiser/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 9, in <module>
    from spotify_ripper.progress import Progress
  File "/home/kaiser/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/progress.py", line 11, in <module>
    import spotify
  File "/home/kaiser/.local/lib/python2.7/site-packages/spotify/__init__.py", line 81, in <module>
    from spotify._spotify import ffi, lib  # noqa
ImportError: /home/kaiser/.local/lib/python2.7/site-packages/_cffi_backend.so: undefined symbol: PyUnicodeUCS4_AsASCIIString

Thanks for help!

**Comment by jrnewell** [comment]
The first message is just telling you that you can upgrade your pip - the Python package manager (although it shouldn't make a difference that it isn't updated).  To upgrade pip
```
pip install --upgrade pip
```

Creating the settings directory ``~/.spotify-ripper`` and copying the key there is correct.

The second error ``undefined symbol: PyUnicodeUCS4_AsASCIIString`` is a new one to me.  After some searching, this [website](http://effbot.org/pyfaq/when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2.htm) says

> If instead the name of the undefined symbol starts with PyUnicodeUCS4, the problem is the reverse: Python was built using 2-byte Unicode characters, and the extension module was compiled using a Python with 4-byte Unicode characters.

That means you should try recompiling your pyenv Python installation with 4-byte unicode characters
```
pyenv uninstall 2.7.10
export CONFIGURE_OPTS="--enable-unicode=ucs4"
pyenv install 2.7.10
pip install --upgrade pip
pip install spotify-ripper
```

Let me know if that helps... good luck!

**Comment by Candelero** [comment]
Thanks a lot, now it is working!

**Comment by akalongman** [comment]
Thanks!
