### ISSUE TITLE
Crash with some type of playlist

### ISSUE THREAD

**Issue by andxet** [jrnewell/spotify-ripper#163]
I tried to download my playlists with the option --playlist-m3u but spotify-ripper crash when it try to create the .m3u file for this type of playlits:
playlists with "/" in the name
playlists with local files (Like iTunes imported playlists)

I think it is simple to recreate the crash, so I don't provide a call stack (and also because it happened yeasterday and I have lost them)

I solved renaming the playlist and deleting the local files.
I hope I was helpful!

**Comment by jrnewell** [comment]
Should be fixed in version ``2.7.5``.
