### ISSUE TITLE
Leading "0" for {track_index}, {index} etc.

### ISSUE THREAD

**Issue by connorxxl** [jrnewell/spotify-ripper#168]
The ripper works perfectly, thanks alot!

Is there a chance to include leading zeros with all the numbers like track_index, index etc.?

Thanks alot.

**Comment by jrnewell** [comment]
Yes, you can already do that by including the number of zero padding you want with the {index}.  For example {track_index:3} {index:3} for zero padding of 3 digits.

**Comment by connorxxl** [comment]
Thanks!
