### ISSUE TITLE
Not getting 320kbps files

### ISSUE THREAD

**Issue by Virkan** [jrnewell/spotify-ripper#170]
Running the tool with the default settings (quality of 320 kbps), I have noticed that all of the mp3 files I get out are always less than 320 kbps. They seem to range on a per song basis of around 220-270 kbps.

For example running the tool on a very recent song (so 320kbps should be available):

spotify-ripper -u  <user> spotify:track:1UfBAJfmofTffrae5ls6DA

Gives me a file that is only 226kbps.

Am I missing something?

**Comment by portableko** [comment]
It's because the default encoding is VBR with a quality setting of "0" try using this: "spotify-ripper  -b 320 -c -u spotify:track:1UfBAJfmofTffrae5ls6DA" or just adding "-c"

**Comment by Virkan** [comment]
Ah thank you very much! Works great now.
