### ISSUE TITLE
No "ph" in spotify region charts

### ISSUE THREAD

**Issue by portableko** [jrnewell/spotify-ripper#172]
Can you add "ph" (philippines) in region charts. thanks

**Comment by jrnewell** [comment]
ok fixed in ver ``2.7.4``.

**Comment by portableko** [comment]
Thanks Jrnewell, btw can i send you a private message to a link about this spotify downloader that works on windows with just using libspotify.dll, "main exe" and appkey. it's a C++ source. maybe you can help me make it rip in vbr mode. thanks in advance.
