### ISSUE TITLE
Label → Grouping metadata

### ISSUE THREAD

**Issue by thibmaek** [jrnewell/spotify-ripper#174]
Is it possible to get the label from spotify and send it to the grouping metadata field (specifically for iTunes)? Or any way to manipulate the metadata?

**Comment by jrnewell** [comment]
like... you want to put in a hardcoded string into the grouping metadata tag or something like title, artist, etc...?

**Comment by thibmaek** [comment]
At the bottom of a release page is the data for the label that released it.
I use the grouping field in iTunes to act as a label field so I can quickly filter my albums one 1 specific label.
Would be ideal if I could send the label data from spotify to the grouping field.

**Comment by thibmaek** [comment]
This is not a general text label in case you misunderstood, I'm talking about the actual music label.

**Comment by jrnewell** [comment]
You mean like the copyrights at the bottom (e.g. '2004 EMI Music')?

**Comment by thibmaek** [comment]
Yep! But without the year preferably (though with the year works as well!)

**Comment by jrnewell** [comment]
I added ``{copyright}`` and ``{label}`` to the format option in version ``2.7.6``.  I still need to make a ``--grouping-tag`` option...

**Comment by jrnewell** [comment]
OK.  Should be available in version ``2.8.0``.

**Comment by thibmaek** [comment]
The option works as expected but still includes a bug I think:
```
…
Adding grouping: {
…
```

It's only adding a bracket instead of the label reading the following line from config.ini: `grouping = {label}`

**Comment by jrnewell** [comment]
ah yeah, i forgot to add the --grouping option to the config.ini handler

**Comment by thibmaek** [comment]
All works as expected now, thanks for implementing!
