### ISSUE TITLE
Cursor error

### ISSUE THREAD

**Issue by smehernosh** [jrnewell/spotify-ripper#179]
Can't seem to understand what's wrong?

mehernosh:~/.spotify-ripper$ spotify-ripper -h
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.8.0', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/bin/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper/ripper.py", line 9, in <module>
    from spotify_ripper.progress import Progress
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper/progress.py", line 5, in <module>
    from colorama import Cursor
ImportError: cannot import name 'Cursor'

**Comment by jrnewell** [comment]
hmm that is strange... there may have been a regression in the setup script for 9.8.0.  Can you try reinstalling 9.8.1?
```
pip uninstall -y spotify-ripper
pip install spotify-ripper
```

If that doesn't work, just install colorama manually
```
pip install colorama
```

**Comment by smehernosh** [comment]
```
mehernosh:~/.spotify-ripper$ pip uninstall -y spotify-ripper
Can't uninstall 'spotify-ripper'. No files were found to uninstall.
```

```
mehernosh:~/.spotify-ripper$ pip install spotify-ripper
Requirement already satisfied (use --upgrade to upgrade): spotify-ripper in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): pyspotify==2.0.5 in /usr/local/lib/python3.4/dist-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.3.3 in /usr/local/lib/python3.4/dist-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): mutagen==1.30 in /usr/local/lib/python3.4/dist-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /usr/local/lib/python3.4/dist-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): schedule>=0.3.1 in /usr/local/lib/python3.4/dist-packages (from spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.0.0 in /usr/local/lib/python3.4/dist-packages (from pyspotify==2.0.5->spotify-ripper)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python3.4/dist-packages (from cffi>=1.0.0->pyspotify==2.0.5->spotify-ripper)
Cleaning up...
```


```
mehernosh:~/.spotify-ripper$ pip install colorama
Requirement already satisfied (use --upgrade to upgrade): colorama in /usr/local/lib/python3.4/dist-packages
Cleaning up...

```

**Comment by jrnewell** [comment]
That is weird... it won't let you uninstall it but it says you have it already?  According to [this](http://stackoverflow.com/questions/13136060/why-cant-pip-uninstall-pysqlite), you just manually delete the folders
```
cd /usr/local/lib/python3.4/dist-packages
rm -rf spotify_ripper* #(or spotify-ripper, might want to see what's there)
pip install spotify-ripper
```

**Comment by smehernosh** [comment]
Thanks it's working now
