### ISSUE TITLE
Is --quality options runs?

### ISSUE THREAD

**Issue by Pepetops** [jrnewell/spotify-ripper#180]
Hi... I try the songs downloaded 160 quality but still putting the option in the config.ini file or -Q option 160, the songs are still being downloaded to an average of 260. Is it normal?
Regards

**Comment by jrnewell** [comment]
I think the output file's bitrate it determined more by the settings to the encoder (for example for mp3s, ``--vbr`` if using vbr mode or ``--bitrate`` if using cbr mode).  The ``-Q`` option determines the bitrate of the stream that Spotify will pass to spotify-ripper and will be passed to your encoder of choice.  So if think in your case, you might want to make the --vbr mode higher (worse quality).

**Comment by Pepetops** [comment]
Hi, thanks for your response. Basically I wonder if down some quality songs were downloaded faster and, logically, had a smaller size. I do not know if download is always at 320 and then when passing them to mp3 is when the -Q option is used?  Well now I use -c -b 192 instead of -Q 160 and seems works... Thanks

**Comment by jrnewell** [comment]
At least with my experience the quality of the stream doesn't seem to be a large factor in ripping speed.  There seems to be a limit in libspotify in how quickly data is made available to the script that is largest bottleneck.
