### ISSUE TITLE
It is not a problem but a question ... How to ripper a spotify's charts

### ISSUE THREAD

**Issue by Pepetops** [jrnewell/spotify-ripper#181]
Hi I don't know how to rip tracks from Spotify's charts...
What's the different names of charts?
For example, if I want to download the global list 50 how should I write?
Thanks

**Comment by jrnewell** [comment]
An example charts URI is ``spotify:charts:regional:global:weekly:latest``.  It basically follows the format of this website: https://spotifycharts.com/regional/.  You can switch the word ``regional`` with ``viral`` (i am not 100% sure what the diff between the two is - i guess a diff algorithm), ``weekly`` with ``daily``, ``global`` with a region such as ``gb``, and ``latest`` with a date such as ``2016-01-21`` if you have it set to ``daily``.

**Comment by Pepetops** [comment]
Thanks, I knew that but wanted to see if I could adjust to that list in particular that I said, the global 50, not the viral ...
