### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by xtwistedmetal** [jrnewell/spotify-ripper#184]
When ever I try to run a command i get segmentation fault (core dumped). Even when just trying to run the command in the wiki 
spotify-ripper -u userhere spotify:track:52xaypL0Kjzk0ngwv3oBPR
Am I doing something wrong, I believe I updated the program correctly recently, I'm running in a VMbox and it the command was just working fine yesterday.

**Comment by jrnewell** [comment]
did you manage to resolve this on your own?  If it was complicated, let me know so I can decide to make a change or added notes to the help wiki.

**Comment by xtwistedmetal** [comment]
It was easy to follow and everything, I just randomly had an issue with it saying segmentation fault, I reinstalled and got it working now, even tested a few tracks. Now I'm just working on getting a playlist ripped but I dislike how .spotify-ripper is a root file, I'm figuring out how to make it accessible/editable on my user If that makes sense.
