### ISSUE TITLE
Missing instruction on OSX setup

### ISSUE THREAD

**Issue by lnmunhoz** [jrnewell/spotify-ripper#186]
After `pyenv global 2.7.11`, when I type `pip`, the command was not found. This is because we have to 
`eval "$(pyenv init -)"` to initialize pyenv properly.

**Fonts**
https://github.com/yyuu/pyenv#homebrew-on-mac-os-x

**Comment by jrnewell** [comment]
I do have pyenv init in the instructions but it is added to .bash_profile so it is executed automatically on each terminal start.
```
$ echo 'if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi' >> ~/.bash_profile
## restart terminal ##
```
I guess I can modify it so you run ``eval "$(pyenv init -)"`` first so you don't need to restart your terminal...

**Comment by lnmunhoz** [comment]
Yes sorry! Maybe for python beginners like me is useful :)

Em sex, 11 de mar de 2016 13:33, James Newell <notifications@github.com>
escreveu:
