### ISSUE TITLE
Scan for incomplete files

### ISSUE THREAD

**Issue by wessel145** [jrnewell/spotify-ripper#189]
Hi,

Sometimes my internet connection drops or any reason spotify ripper stops his work.
Anyway, When it stops in the middle of ripping a song, the file still exists but with only the first half of the song in it.

Is there any way to scan for incomplete files and overwrite them? using --overwrite is not really an option because it will overwrite all my songs in that playlist

**Comment by jrnewell** [comment]
I think I added this in ``2.8.4``...

**Comment by jrnewell** [comment]
Sorry it was ``2.8.5``... can you pleas try?

**Comment by wessel145** [comment]
Tried and worked! many thanks!
KUTGW

**Comment by wessel145** [comment]
Edit, i did not upgrade. i thought it worked but it didn't
Since i updated i get the following errors:

`Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 226, in run
    self.progress.calc_total(all_tracks)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/progress.py", line 69, in calc_total
    not is_partial(audio_file, track):
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 399, in is_partial
    audio_file_dur = audio_file_duration(audio_file)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 394, in audio_file_duration
    _file = mutagen.File(audio_file)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 184, in File
    from mutagen.asf import ASF
  File "/usr/local/lib/python2.7/dist-packages/mutagen/asf/__init__.py", line 14, in <module>
    from mutagen._util import resize_bytes, DictMixin
ImportError: cannot import name resize_bytes`

**Comment by jrnewell** [comment]
That is really weird... it looks like you have mutagen 1.31 installed since that asf directory doesn't exist in 1.30 (you can confirm this with ``pip list``).  I am not sure how you got it installed though because the mutagen requirement for spotify-ripper is fixed at 1.30.  Anyway you can force the installation of a version using pip:
```
pip install mutagen==1.30
```

**Comment by wessel145** [comment]
Thanks for the fast reply, my pip lists says i'm on the right version. 
Here is the output of `pip list`

```
bottle (0.12.7)
cffi (1.5.2)
characteristic (0.1.0)
chardet (2.3.0)
Cheetah (2.4.4)
colorama (0.3.3)
configobj (5.0.6)
cryptography (1.3.1)
deluge (1.3.10)
dnspython (1.12.0)
enum34 (1.1.2)
feedparser (5.1.3)
gpiozero (1.1.0)
idna (2.1)
ipaddress (1.0.16)
lxkeymap (0.1)
Mako (1.0.0)
MarkupSafe (0.23)
mcpi (0.1.1)
meld3 (1.0.0)
mutagen (1.30)
numpy (1.8.2)
PAM (0.4.2)
picamera (1.10)
pifacecommon (4.2.1)
pifacedigitalio (3.1.0)
Pillow (2.6.1)
pip (8.1.1)
ply (3.4)
pyasn1 (0.1.9)
pyasn1-modules (0.0.5)
PyBluez (0.18)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.19.5)
pygame (1.9.2a0)
pygobject (3.14.0)
pyliblzma (0.5.3)
pyOpenSSL (16.0.0)
pyserial (2.6)
pyspotify (2.0.5)
pysqlite (1.0.1)
python-libtorrent (0.16.18)
pyxdg (0.25)
requests (2.9.1)
RPi.GPIO (0.6.2)
RTIMULib (7.2.1)
schedule (0.3.2)
sense-hat (2.1.0)
service-identity (1.0.0)
setuptools (20.6.7)
simplejson (3.6.5)
six (1.10.0)
spidev (3.0)
spotify-ripper (2.8.5)
supervisor (3.0)
Twisted-Core (14.0.2)
Twisted-Web (14.0.2)
urlgrabber (3.9.1)
uTidylib (0.2)
yenc (0.4.0)
yum-metadata-parser (1.1.4)
zope.interface (4.1.1)
```

**Comment by jrnewell** [comment]
That is strange because you seem to have both 1.30 and 1.31 code.  Can you try uninstalling it and reinstalling 1.30 (or remove that directory and reinstall)?

**Comment by wessel145** [comment]
It worked, i had to uninstall and then remove the remaining files. I reinstalled and it worked like a charm! 'overwriting partial file'!!!!!!! love it!
Many thanks dude!
