### ISSUE TITLE
/Storage directory

### ISSUE THREAD

**Issue by f00b4r4** [jrnewell/spotify-ripper#193]
Hi, (And thanks a LOT for this great working ripper)

so far I have ripped 9.2GB and a "Storage" directory of 10GB.
I would guess that this is where the raw stream is stored?

What exactly is it used for (since it is not called "temp" and is not automatically removed after a finished job)? Does removing the "Storage" directory have a negative effect on skipping already existing downloads or the playlist sync?

If it is the original spotify (ogg?)-music-data, could i use it to make 192kbps-VBR-versions of the music (I ripped 320kbps and now I guess ists not a good idea to transcode AGAIN to make 192kbps-files)

Thanks,
Michael

**Comment by moseslecce** [comment]
I too am wondering this.. I cannot find any documentation about it and there are really no references to this directory in the spotify-ripper code. This leads me to believe that this is part of the lib-spotify package.

You will notice that the contents of this directory, as cryptic as they are, seem to match what you would have on your desktop with the official client.

E.g.

Windows: C:\Users\USERNAME\AppData\Local\Spotify\Storage
OS X: /Users/USERNAME/Library/Caches/com.spotify.client/Storage/
Linux: ~/.cache/spotify/Storage/

The cache is typically used for storing files offline, so presumably if its used it would likely allow you to re-rip a song that was ripped without having to download from the internet.  I can't say for certain that the client does this however.

**Comment by jrnewell** [comment]
Yeah I am pretty sure both of you are correct - it is just a offline cache of the ogg files.  Although I am guessing they might be encrypted so you probably can just open it with VLC and it will work.

I couldn't really find anything to disable offline caching via pyspotify.  I guess I could put something in there to auto rm the storage directory on every run.  What do you think?

**Comment by moseslecce** [comment]
I suppose it depends if the cache is useful for the program, if its useful in that it will help with re-rips then maybe it should be a setting if the cache should be kept or deleted after a run.  Otherwise, deleting it would make sense, and yes it is encrypted.

**Comment by acorven** [comment]
A setting would be nice.

**Comment by jrnewell** [comment]
OK. I added an option ``--remove-offline-cache`` to 2.8.6.  Can you try?
