### ISSUE TITLE
Error saving m3u file for big playlist OR m3u fault for local files?

### ISSUE THREAD

**Issue by hansmueller100000** [jrnewell/spotify-ripper#196]
Hey,

I successfully downloaded a large playlist of me (over 500 songs) but the spotify-ripper is unable to create a full m3u file for it. I may post the full error message if I am back home (script running on a raspberry pi 2 @ Raspbian Jessie).

I noticed that it may have something to do with having local files in a playlist as it's the only playlist I synced which has a few local tracks in it - all the others worked fine.

Taking a look at the m3u file it created (which was canceled/corrupted) I can see that the first few tracks are correctly, but then it stops somewhere. Comparing to the playlist on Spotify I'm pretty sure it's a local file which is (of course) skipped while downloading and it seems like the m3u-create-algorithm doesnt get that?

Thank you in advance and thank you very much for your program, I finally dont need to let my computer on for days consuming a huge ammount of power for just downloading a few tracks, doing it on my raspberry is pretty senseful and your script even had more options than every other program I used so far! I was about to try coding one myself if I have time but your program is just THE program I was always looking for. :+1:

**Comment by hansmueller100000** [comment]
It also relatively often says these messages if I restart the script with the same playlist:

(Example:)

Loading track...
Overwriting partial file
[ 22 / 660 ] Ripping spotify:track:5XJJdNPkwmbUwE79gv0NxK

**Comment by jrnewell** [comment]
Were you able to create an full m3u file for a large playlist without local files?

**Comment by jrnewell** [comment]
I put in a skip for local files in the m3u and wpl file generation code.  Can you check to see if that helps with your issue.  It is in 2.8.6.
