### ISSUE TITLE
Not working - Missing module?

### ISSUE THREAD

**Issue by psychosteve** [jrnewell/spotify-ripper#2]
Getting an error everytime i use any type of use example... doesn't make sense! :( 

<pre><code>Lloyds-MBP:spotify-ripper Lloyd$ ./ripper.py -u ******* -p ******* spotify:user:*******:playlist:2CWAbUXA4zxiPtifeWZv0s
Traceback (most recent call last):
  File "./ripper.py", line 7, in <module>
    from colorama import init, Fore
ImportError: No module named colorama
</pre></code>

**Comment by psychosteve** [comment]
Fixed it! Just needed to install colorama. Silly moment lol. <pre><code> pip install colorama</pre></code>

**Comment by jrnewell** [comment]
I will add colorama to the list of dependencies in the README.
