### ISSUE TITLE
Songs get saved to wrong playlist

### ISSUE THREAD

**Issue by hansgoed** [jrnewell/spotify-ripper#203]
Hi,

I just updated from 2.8.4 to 2.8.6 and started ripping. 

- My format is `{playlist}/{track} - {artist}.{ext}`. 
- I use playlist url's to define the songs to be ripped.

The folder that is picked is the name of the last playlist. All songs from every playlist seem to end up here.

Also, deleting partially ripped files seems to get the playlist folder wrong (not while determining, just when deleting).

**Comment by jrnewell** [comment]
Can you show some logs, arguments and options you are using?  I am having trouble replicating the issue you are having.

**Comment by ilteoood** [comment]
@jrnewell watch my issue, the one down here. I have the same problem, but more details.
[https://github.com/jrnewell/spotify-ripper/issues/199](url)

**Comment by jrnewell** [comment]
I think I solved this regression in ``2.8.8``.  Can you verify?

**Comment by hansgoed** [comment]
Sorry for getting back to you this late. 

I can verify this problem has been solved. Thank you very much!
