### ISSUE TITLE
Multiple Albums wrong directory

### ISSUE THREAD

**Issue by davze** [jrnewell/spotify-ripper#205]
When ripping a list of albums from different artists from a txt file all albums are saved in the folder of one artist.

Example:
Mumford & Sons - Blurryface
Coldplay - A head full of dreams
Mighty Oaks - Howl

All three albums will be saved in the Mumford & Sons folder.

**Comment by ilteoood** [comment]
+1, same here!

**Comment by jrnewell** [comment]
I think I solved this regression in ``2.8.8``.  Can you verify?

**Comment by davze** [comment]
Can confirm that issue is resolved.
