### ISSUE TITLE
Play token lost, aborting...

### ISSUE THREAD

**Issue by dieterhatnkleinen** [jrnewell/spotify-ripper#206]
When I try to rip a playlist, I always get the error above and it stops ripping.
It does not even finish a single song.

**Comment by wessel145** [comment]
Are u using spotify to 'listen' music while you're ripping? This probably happens because you or someone else is using the account to listen to music on spotify, and spotify only allows 1 listeren at the same time at 1 account

**Comment by dieterhatnkleinen** [comment]
makes sense, thanks!
