### ISSUE TITLE
Logged in failed: USER_NEEDS_PREMIUM

### ISSUE THREAD

**Issue by Nivgov** [jrnewell/spotify-ripper#208]
I don't know why I have to be a premium account so I can use the ripper... I downloaded this tool so I don't have to pay for a premium account and I can't use it because of it.
I have an appkey but I still can't use it.

**Comment by jrnewell** [comment]
I am not sure why you are need premium to stream from libspotify, but unfortunately it something that Spotify enforces.  This is something not really in my control, sorry.
