### ISSUE TITLE
Keep program running on play-token lost

### ISSUE THREAD

**Issue by daniel-tigges** [jrnewell/spotify-ripper#213]
If the play token was lost the program terminates. It would be nice to configure a timeout so that the program continues after loosing the play token.

**Comment by jrnewell** [comment]
so it would just interrupt whoever is listening to Spotify on that account after the timeout?

**Comment by daniel-tigges** [comment]
Yes right! But imho there are some use-cases where such a behavior could be useful. For me  it would be nice if after the play-token is gone, the program stays idle until after a certain timeout (or a specific time in 24hr format) it starts ripping again.

**Comment by jrnewell** [comment]
I added this to ``2.9.0`` using the ``--play-token-resume`` option
