### ISSUE TITLE
flac encoding with comp option.

### ISSUE THREAD

**Issue by seandex** [jrnewell/spotify-ripper#216]
in config.ini

flac = true
comp = 0

'comp' does not set the compression complex. it is default by 8 all the time.

'spotify-ripper --comp 0' works.
but in config.ini it does not.

i'm sorry if im mis-using it.

**Comment by jrnewell** [comment]
I think I fixed this in ``2.9.0``, can you check?

**Comment by seandex** [comment]
It was fixed 2.8.9 already haha thank you!!
