### ISSUE TITLE
Incorrectly working --playlist-sync + crash on local files

### ISSUE THREAD

**Issue by hansmueller100000** [jrnewell/spotify-ripper#224]
Hey,

I have two new issues.

______________________

**Issue one: --playlist-sync**

___________

I tried to use the --playlist-sync feature now as I've previously downloaded a playlist using that parameter so is logs all locations of the songs.

Sadly it's not really working. Yes, it does skip many tracks, but sadly no, it doesnt update the track numbers. I'm especially refering to the "Top 100 tracks" playlists by Spotify, now I have many numbers appearing more than one time and many numbers missing, but every song is there, just the order is wrong. To be more clearly: The Top 100 looks now like this: 

0001 - Alan Walker - Faded
0001 - Drake - One Dance
0002 - Twenty One Pilots - Stressed Out
0003 - ...
....
0008 - ...
0010 - ...

Even though the order of the --playlist-m3u is correct.

" For example, if your format string is {index} {artist} - {track_name}.{ext}, it will rename is existing files so the index is correct. "  -  So this is the part that does not work for me. My format is 
" {playlist}/{index:4} - {artist} - {track_name}.{ext} "

______________________

**Issue two: crash when syncing local files**

___________

I submitted an issue before which let the --playlist-m3u feature to crash when having local tracks in a playlist. Sadly it seems that in the most recent version local files are completely crashing the ripper.

Here is the error I get when trying to add a playlist with local files in it:

`Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 227, in run
    audio_file = self.format_track_path(idx, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 585, in format_track_path
    format_track_string(self, args.format[0].strip(), idx, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 175, in format_track_string
    album_browser.load()
  File "/usr/local/lib/python2.7/dist-packages/spotify/album.py", line 264, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/spotify/utils.py", line 242, in load
    _check_error(obj)
  File "/usr/local/lib/python2.7/dist-packages/spotify/utils.py", line 206, in _check_error
    error_type, ignores=[spotify.ErrorType.IS_LOADING])
  File "/usr/local/lib/python2.7/dist-packages/spotify/error.py", line 31, in maybe_raise
    raise LibError(error_type)
LibError: General permanent error
`

So you have any clue why this is happening now?

______________________

Thank you very much for creating such an amazing tool and giving us your time to work out the few issues it has.

Best regards

**Comment by seandex** [comment]
i also confirmed that sync isn't working.

**Comment by hansmueller100000** [comment]
**Update regarding issue one:**
Seems like calling the ripper without the --playlist-m3u option and repeating the call 2 to 3 times makes the ripper actually rename the songs. Could you please fix that? Thanks! :)


**Update regarding issue two:**
I actually have no idea if it's the local files right now as I removed all of them of the playlist I want to sync and it's not syncing either, still getting the same error message.
Would be nice to see that fixed as I'm trying to sync a playlist which is over 500 songs big.
