### ISSUE TITLE
Logging in... Logged in failed: USER_NEEDS_PREMIUM ???????

### ISSUE THREAD

**Issue by donfisico** [jrnewell/spotify-ripper#226]
Hi, after getting that I need to use sudo for using spotify ripper, I get now with a new problem:

> $ sudo spotify-ripper -u _myspotifyuse_r -p _mypass_ spotify:track:2zYzyRzz6pRmhPzyfMEC8s 
> Spotify Ripper - v2.8.9
>   Encoding output:	MP3, VBR 0
>   Spotify bitrate:	320 kbps
>   Unicode support:	Yes
>   Output directory:	/home/mylinuxuser
>   Settings directory:	/home/mylinuxuser/.spotify-ripper
>   Format String:	{album_artist}/{album}/{artist} - {track_name}.{ext}
>   Overwrite files:	No
> Logging in...
> Logged in failed: USER_NEEDS_PREMIUM
> Encountered issue while logging into Spotify, aborting...
wich seems to mean that: I NEED TO BE A SPOTIFY PREMIUM USER TO USE SPOTIFY-RIPPER????

**Comment by Fiddlesteak** [comment]
Uhm yes, you need to log in with spotify premium account to use the spotify-ripper, otherwise you can't use it

**Comment by asoretmadolell** [comment]
Yep. It says so on the README and the webpage

**Comment by donfisico** [comment]
Pfff, the whole joke of using spotify-ripper would be not needing an premium account to use it! I mean, it is trying to ripp the songs! Someone with premium account can use the option "get if offline" for listening to the songs offline! Even I bet there is a way to get the "offline" songs downloaded and convert them into mp3 songs !!!! I really do not get it!

**Comment by Fiddlesteak** [comment]
You are completely wrong. Besides that you already need a premium account for the spotify_appkey.key, the point is that spotify-ripper uses the cache for offline-files to get the audiostream and convert this PCM stream in for example mp3.
Also, the offline function for premium is only available as long as you have premium. If you don't renew your premium, subscription, your offline function would be disabled and you couldn't listen to the songs anymore but the songs that you ripped to a permanent file will stay without any time limit. Also, a lot of people like to listen to their music with their favorite music player and will therefore rip the songs from spotify to do so.
The offline-files of spotify are strongly encrypted and it is very hard to crack that encrypted files open (one of the reasons for that is that the way there are encrypted changes from song to song). However, there is a way to emulate an OS supporting spotify with qemu on your linux and then record the system with PANDA to get the decrypted oggs but that is very hard for people who don't know how to work with that stuff so there is no way to just "convert" the offline songs to mp3.

**Comment by Fiddlesteak** [comment]
also this is no issue anymore so close pls

**Comment by donfisico** [comment]
Fiddlesteak: First of all you do not really need a premium account for the spotify_appkey.key, if you search it enough on google (ar any other web searcher) you will find a place to download such file, as I have done myself. Secondly: in some sense you are giving me the reason, because as you say, and I quote: 

> Also, the offline function for premium is only available as long as you have premium. If you don't renew your premium, subscription, your offline function would be disabled and you couldn't listen to the songs anymore but the songs that you ripped to a permanent file will stay without any time limit.

So a good reason for using spotify-ripper is  not needing to mantain (at least) an premium account for listening to your songs offline. 
Thirdly: with all your respect, I thought (and I need to be clear on this: I thought wrong, my mistake this time) this spotify-ripper project was a little bit "pirate" in the sense of the pourpose was to get the music for free, free information (whatever you want to call it). If you already paying for spotify-premium there is no sense of it. 
 And by the way: posting "also this is no issue anymore so close pls", it is very bad taste. It is the administrator of the forum wich will decide to close this post or not. Although I can bet it will be closed, you do not need to rush him/her; because this post does not hurt you, or it does?

**Comment by jrnewell** [comment]
The restriction that you need premium to stream using libspotify is something that Spotify enforces, not this script.  You can use someone else's app_key file, but Spotify does the check for premium status against the account you are using to login at the start of the script.  

Whether if the script is useful for you or not given that fact - that is really more of a personal thing.  I think some people use it for syncing their playlist on their older iPods that don't have Spotify.
