### ISSUE TITLE
cover-file option bug up from 2.8.7

### ISSUE THREAD

**Issue by detoxxx** [jrnewell/spotify-ripper#227]
hy James!

When i use the --cover-file optional argument the result is only one cover.jpg 4 example and this message:

Spotify error detected
'Namespace' object has no attribute 'cover_embed'
Skipping to next track...
Deleting partially ripped file

my investigation according the problem is in the "tags.py" probably the new function implement was not correct between 2.8.6 and 2.8.7 version:
"Add --cover-file-and-embed option (bhelm)"
...now it's your turn maybe.

btw: Thx 4 your great usefull stuff! ;)

**Comment by jrnewell** [comment]
Should be fixed in ``2.9.0``.

**Comment by detoxxx** [comment]
thx 4 fix! works fine 8)
