### ISSUE TITLE
undefined symbol fix (incorrect syntax in the Wiki)

### ISSUE THREAD

**Issue by nwillemse** [jrnewell/spotify-ripper#235]
Hi,

I ran into the undefined symbol error that's the last issue in the Wiki, but it looks like the syntax is incorrect for the fix.  I had to use the following command to reinstall python correctly to get it to work:

$PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2" pyenv install 2.7.11

It would be great if you can update the Wiki.

Thanks

**Comment by jrnewell** [comment]
do you mean that you used ``ucs2`` or that you are using the env var ``PYTHON_CONFIGURE_OPTS`` instead of just ``CONFIGURE_OPTS``?  I will add something for ucs2 since you are not the first person that had this issue.

**Comment by nwillemse** [comment]
Hi,

BTW I am on MacOS 10.11.5

This doesn't work. I just tested it: `CONFIGURE_OPTS="--enable-unicode=ucs2"`

But the following works fine to fix this error:

```
$ export PYTHON_CONFIGURE_OPTS="--enable-unicode="ucs2"
$ pyenv install 2.7.10
$ pip install spotify-ripper
```

Thanks
NickW

**Comment by jrnewell** [comment]
OK.. I have had different people tell me different things about what works for them, so I added a note about using ``PYTHON_CONFIGURE_OPTS`` if the original doesn't work.  Let me know if you don't think the wiki is clear.

**Comment by nwillemse** [comment]
Ok, thanks. Also I had to use UCS2 instead of UCS4...
