### ISSUE TITLE
Can I save the Raw Pcm file and Mp3 at the same time?

### ISSUE THREAD

**Issue by calixto111** [jrnewell/spotify-ripper#236]
Hi Jrnewell, is it possible to save a raw pcm file and Mp3 at the same time ,but put them in 2 separated folders inside the artist folder , I mean one folder for pcm and one for mp3 in the same artist album folder?

**Comment by jrnewell** [comment]
hmm it could be possible - but the script is currently not setup to do it that way :smile:  I can you show you how to make a customized version of spotify-ripper?

**Comment by calixto111** [comment]
Thank you , that is very good ...
just let me know how to do it
I would like the script to be able to save different formats

thanks 

Cal.

**Comment by kz0** [comment]
Is it possible to share the code for other users?

Thanks.

**Comment by calixto111** [comment]
Of course , it would be nice
Thanks

Sent from my iPhone

On Jul 18, 2016, at 8:15 PM, kz0 <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible to share the code for other users?

Thanks.

**Comment by kz0** [comment]
@calixto111 can you point me to the changes then?

**Comment by jrnewell** [comment]
ok, i changed my mind on this and added ``--plus-pcm`` and ``--plus-wav`` in ver ``2.10.0``

**Comment by calixto111** [comment]
Very good , thank you
Can you please also add -plus-flac  ?

Thank you very much

Sent from my iPhone

On Jul 20, 2016, at 9:47 AM, James Newell <notifications@github.com<mailto:notifications@github.com>> wrote:


ok, i changed my mind on this and added --plus-pcm and --plus-wav in ver 2.10.0
