### ISSUE TITLE
Where is config.ini file on macbook pro El Capitan ?

### ISSUE THREAD

**Issue by calixto111** [jrnewell/spotify-ripper#238]
Hi , 
Where is the config.ini file on a Macbook pro [ El Capitan]  ?
I show unhiden files and flolders and still don't see it.

Thank you in advance 

Cal.

**Comment by jrnewell** [comment]
It doesn't exist by default - you have to create it.  It goes under
``
~/.spotify-ripper
``

**Comment by calixto111** [comment]
Thank you very much Jrnewell,
Do I have to create it using textedit with extension .ini?
if not how can I do it
Can I please download a copy of it from any place so I can edit it afterwards ?

thanks

**Comment by calixto111** [comment]
oh , never mind ... I got it working 

Thank you Jrnewell
