### ISSUE TITLE
How to function the option resume-after and stop-after

### ISSUE THREAD

**Issue by xidoc** [jrnewell/spotify-ripper#246]
Hi jrnewell !

How to function the argument resume-after and stop-after ?

It's possible to resume spotify-ripper after for example 1h00 and resume after ?

Ok I found --partial-check weak

Thank you for spotify-ripper

**Comment by jrnewell** [comment]
you can give both ``--stop-after`` and ``--resume-after`` a time interval.  So ``--stop-after 2h --resume-after 1h`` will run the script for 2 hours and then pause for one hour, then run for 2 hours then pause for one hour, repeat.

If you only do ``--stop-after 2h`` it will just end the script after two hours.
