### ISSUE TITLE
ascii codec can't encode characters

### ISSUE THREAD

**Issue by lavolp3** [jrnewell/spotify-ripper#248]
System: Raspberry Pi 3 running Debian (osmc), spotify-ripper 2.9.1, python 2.7.10

I have the above mentioned issue everytime I try to work on a list of several albums stored as URIs in a file.
The programm tries to skip the track afterwards, but unfortunately crashes with a UnicodeEncodeError:

> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 85: ordinal not in range(128)

I have not used any -ascii option

Thanks for helping.

![screenshot_2016-06-22-08-43-35](https://cloud.githubusercontent.com/assets/20084205/16258408/101fd1b2-385e-11e6-861d-d6c78ac55972.jpg)

**Comment by rogovdm** [comment]
Same bug.

**Comment by lavolp3** [comment]
This obviously happens everytime a special character not included in the standard ascii table (128) is being encoded.
In the README you state that normally utf8 is used, which should be able to deal with these characters., afaik. 
However, the program seems to be using ascii encoding...

**Comment by lavolp3** [comment]
In 2.10.1 things seem to have changed a bit.
In 2.9.1 there were several palces were encoding was a problme. Some of them have been fixed.

However I still have one error in tags.py.
Seems to be resolved if you let cover_file being encoded as below:

`                    if not path_exists(cover_file):
                        cover_file = cover_file.encode('utf8', 'replace')
                        with open(cover_file, "wb") as f:
                            f.write(enc_str(image.data))
 `

**Comment by jrnewell** [comment]
good catch! Although I don't think that you need to encode the binary data, but the file name should be encoded like you said.  I tried to apply your suggestion to ``2.10.2``.

**Comment by lavolp3** [comment]
The issue is mostly solved within the new version. 
Thanks for that!

I just had problems with a mutagen file creating a UnicodeError which I had to resolve manually. But that does not belong into this repository.
