### ISSUE TITLE
Logged in failed: UNABLE_TO_CONTACT_SERVER

### ISSUE THREAD

**Issue by danielb1234** [jrnewell/spotify-ripper#254]
Yesterday everything worked fine using my facebook account. Today I can't even login to Spotify desktop and web player. Using spotify-ripper I get this error.

Daniels-MacBook-Pro:~ Daniel$ spotify-ripper -u 1110520222 spotify:track:5BgaqHw6dR0ldxsfeE2FBr -d /Users/Daniel/Downloads
Spotify Ripper - v2.10.1
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/Users/Daniel/Downloads
  Settings directory:	/Users/Daniel/.spotify-ripper
  Format String:	{album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Password: 
Logged in failed: UNABLE_TO_CONTACT_SERVER

Thanks

**Comment by jrnewell** [comment]
The spotify desktop and webplayer aren't really connected to the spotify-ripper script.  It sounds like there is some issue with the spotify server you are connecting to or something with your ISP/internet connection.

**Comment by danielb1234** [comment]
I don't know why but everything works again :) Thanks

**Comment by jrnewell** [comment]
cool!
