### ISSUE TITLE
V 2.10.1 does not work - Output directory set to '/'

### ISSUE THREAD

**Issue by lavolp3** [jrnewell/spotify-ripper#255]
Traceback is:

> Spotify Ripper - v2.10.1
>   Encoding output:      MP3, VBR 0
>   Spotify bitrate:      320 kbps
>   Unicode support:      Yes
>   Output directory:     /
>   Settings directory:   /home/osmc/.spotify-ripper
>   Format String:        {album_artist}/{album}/{track_num:2} - {track_name}.{ext}
>   Overwrite files:      No
> Traceback (most recent call last):
>   File "/home/osmc/.pyenv/versions/2.7.10/bin/spotify-ripper", line 9, in <module>
>     load_entry_point('spotify-ripper==2.10.1', 'console_scripts', 'spotify-ripper')()
>   File "/home/osmc/.pyenv/versions/2.7.10/bin/main.py", line 522, in main
>     ripper = Ripper(args)
>   File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 89, in __init__
>     self.post = PostActions(args, self)
>   File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/post_actions.py", line 32, in __init__
>     _base_dir, args.fail_log[0]), 'w', encoding)
>   File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/codecs.py", line 884, in open
>     file = __builtin__.open(filename, mode, buffering)
> IOError: [Errno 21] Is a directory: u'/'

New version (downloaded 15 min ago) seems to mess with the output directory.
I have set /media/downloads... as directory, and it worked with 2.9.1.
Have downgraded to 2.9.1 and it works again

**Comment by jrnewell** [comment]
Hmm.. I didn't see the output dir go to "/" when I played around with the --directory option in just now.  What are the arguments and config.ini that you are using (with any personal info redacted)  and which linux distro are you using?

**Comment by lavolp3** [comment]
I'm using osmc/Debian release 4.4.8-3 osmc
config.ini:

> [main]
> format = {album_artist}/({year}) {album}/{track_num:2} - {track_name}.{ext}
> last = True
> directory = /media/downloads/spotify/
> ascii = False
> #log = logfile2.log
> cover-file-and-embed = cover.jpg
> fail-log = /home/osmc/.spotify-ripper/fail.log

Not using any arguments.

I'll try again as soon as I'm done working on the problems I have with non-ascii characters (see other issue "ascii-codec" :-) )

Thanks

**Comment by lavolp3** [comment]
Sorry for the confusion James,
I have reinstalled 2.10.1 and now it works.

**Comment by jrnewell** [comment]
whew, that makes my life easier :)
