### ISSUE TITLE
Argument format - add spotify URI

### ISSUE THREAD

**Issue by Arcasss** [jrnewell/spotify-ripper#256]
Hello everyone,
is it possible to use --format option with spotify uri link?
I'd like to add comment to ripped song with original spotify URI.

Example:
Song Let it Snow from Cascada would have mp3 id tag comment - "Spotify URI - spotify:track:7tTFND5e30fA49FFLqsEGe"

Thanks

P.S.: Great job

**Comment by jrnewell** [comment]
So you want something like "{track_uri}" for format and comment options which will be replaced with the spotify uri?  Doesn't sound too difficult

**Comment by Arcasss** [comment]
Yes. New options (lets say track_uri) in format settings, which allows user to keep original spotify uri.
For my purposes, I'd put in comment id3tag.

**Comment by jrnewell** [comment]
OK. I added it to version ``2.10.3``.

**Comment by Arcasss** [comment]
Works, thanks!
