### ISSUE TITLE
key location not working

### ISSUE THREAD

**Issue by citizenthr33** [jrnewell/spotify-ripper#257]
Hey all,
i have installed spotify-ripper on my server (ubuntu 14.04) and it is installed correctly. When i start it with a command like **spotify-ripper -u user URI** i get the following prompt:

**Please copy your spotify_appkey.key to /home/test/.spotify-ripper, or use the --key|-k option**

I have the key in the right place and the permissions are all set like on my other machine where the ripper works. When i try to tell the ripper that the key is there with

**spotify-ripper --key /home/test/.spotify-ripper/**
or 
**spotify-ripper --key /home/test/.spotify-ripper/spotify-appkey.key**
i get the promt
**spotify-ripper: error: too few arguments**

I do not know what to do now. Thank you for your help!

**Comment by citizenthr33** [comment]
in the meantime i installed the ripper on:
virtual machine locally 14.04
debian server
fedora server
tried via docker
virtual machine locally ubuntu 14.04 server

always the same error

**Comment by jrnewell** [comment]
Two things:

1.) I think you have a very, very slight typo in your key filename (if you are trying to do the default). It is spotify_appkey.key with an underscore and not a dash between "spotify" and "appkey"

2.) You need include a spotify uri at the end of your argument list like ``spotify:track:52xaypL0Kjzk0ngwv3oBPR``.  That is why you were seeing the "too few arguments" error message.  You can get the uri from the desktop app by right-clicking on a playlist or song and copy the uri.

**Comment by citizenthr33** [comment]
You are right. Now i feel dumb.
The problem was that due to using a bad fileserver all "_" were changed to "-" into the filenames. I did not recognize it because i used my own, working key. I know the URI thing, i am here since version 2.1.1. Anyway, Thank you a lot holy master of spotify :+1: 


sometimes the small things bug you the most.
-dumb user-
