### ISSUE TITLE
Additional summary progress

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#26]
In addition to the (very useful) progress bar shown for individual tracks, it may prove useful to show additional statistics about the rip:

1. The total progress as a bar next to the track's individual progress
2. The time remaining on the track rip and the total rip (as a **calculated guess** using rate calculation)

```
Loading track...
Ripping spotify:track:25C1Tk4EVf4w3jP4GGxGS5
/home/user123456/spotify/classical/Poppy Ackroyd - Aliquot.mp3
Track: [================================        ] 3:46 / 4:32 (0:15 until done)
Total: [==                                      ] 3:46 / 1:15:03 (21:15 until done)
```

From experience, I would say that this requires loading the track objects before starting the rips, as the duration information has only been available to me after loading them using pyspotify.

**Comment by jrnewell** [comment]
I added the per track remaining in version ``1.2.3``.

**Comment by dylanjboyd** [comment]
I am reopening this issue, as I didn't notice the lack of a total progress in the latest version. Is this possible?

**Comment by jrnewell** [comment]
OK.  I made the change to 64548f7 / version ``1.2.4``.
