### ISSUE TITLE
save cover art  as cover.jpg in album folder '' very important for wav ''

### ISSUE THREAD

**Issue by calixto111** [jrnewell/spotify-ripper#264]
Hi, 
Can you please set up an option to save the artwork as cover.jpg in the album folder ?
Some players look for this type of file to play music with artwork  like for music files that don't have it embedded like wav

thank you in advance

**Comment by kz0** [comment]
Have you tried the --cover-file-and-embed option?

**Comment by calixto111** [comment]
Yes  , but it is not cover.jpg
Thank you

Sent from my iPhone

On Aug 6, 2016, at 10:37 AM, kz0 <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried the --cover-file-and-embed option?

**Comment by kz0** [comment]
Just tested it and its working fine.
