### ISSUE TITLE
Separate folders for --plus-pcm  --plus-wav

### ISSUE THREAD

**Issue by calixto111** [jrnewell/spotify-ripper#265]
Hi, 
Can you please make the script to save in 2 separate folders within the album folder when doing --plus-pcm  --plus-wav ?
It would be nice not to have .pcm and the other file format together.
thank you very much in advance

**Comment by kz0** [comment]
Just create a script to move the wav or pcm.

**Comment by calixto111** [comment]
Thank you very much

**Comment by calixto111** [comment]
hi,

Are you going to upload the new update for this to work?

thnaks











________________________________

**Comment by kz0** [comment]
As i mentioned, you just need to create a script on your shell to move the files or folders.

Here's a simple tutorial to get you started: http://www.freeos.com/guides/lsst/ch02sec01.html
