### ISSUE TITLE
Spotify key 

### ISSUE THREAD

**Issue by beboeverbebo** [jrnewell/spotify-ripper#27]
There is a few things I need to get right first, is each key unique to an account?

And once my premium subscription ends, will the method spot working as well?

**Comment by jrnewell** [comment]
1. Sort-of.  The key is per-application, so technically it would probably work if someone distributed their key (Mopidy's plugin does it this way).  However, I don't do this so you need to make your own key.

2. Yes.  It will stop working if you don't have a premium account (although I never tested this).
