### ISSUE TITLE
script with spotify-ripper fails allways if run with cron or at

### ISSUE THREAD

**Issue by Pepetops** [jrnewell/spotify-ripper#270]
Hi,is there any way the script I normally use with spotify-ripper can operate under the command of "cron" or "at". Whenever I have run with these commands, I get an error report that failed spotify-ripper ... Someone has done something that works?
Example:
File "/usr/bin/spotify-ripper", line 11, in <module>
    sys.exit(main())
  File "/usr/bin/main.py", line 587, in main
    stdin_settings = termios.tcgetattr(sys.stdin)
termios.error: (25, 'Inappropriate ioctl for device')
****
Thank you

**Comment by jrnewell** [comment]
Can you try using the ``--log`` option in version ``2.10.5`` and see if that helps?

**Comment by Pepetops** [comment]
OK, I will when I have time and I'll tell you something... Thanks
