### ISSUE TITLE
Overload spotify_ripper.main.main() to receive args

### ISSUE THREAD

**Issue by chuckbutler** [jrnewell/spotify-ripper#28]
I was attempting an integration and noticed the main() method does not receive args. This directly prevents any integration from being able to instantiate an instance of the app, and/or pass it arguments.

This has a byproduct of making the method testable :)

**Comment by jrnewell** [comment]
You mean something like this where you can pass in something else besides using sys.argv?

```python
def main(prog_args=sys.argv[1:]):
    # in case we changed the location of the settings directory where the config file lives, we need to parse this argument
    # before we parse the rest of the arguments (which can overwrite the options in the config file)
    settings_parser = argparse.ArgumentParser(add_help=False)
    settings_parser.add_argument('-S', '--settings', nargs=1, help='Path to settings, config and temp files directory [Default=~/.spotify-ripper]')
    args, remaining_argv = settings_parser.parse_known_args(prog_args)
    
    # etc ....
```

**Comment by chuckbutler** [comment]
Indeed, that would be excellent @jrnewell

**Comment by jrnewell** [comment]
OK.  I made the change to 64548f7 / version ``1.2.4``.
