### ISSUE TITLE
Comments on URI.txt

### ISSUE THREAD

**Issue by rygos** [jrnewell/spotify-ripper#282]
Hi,

it would be nice to have the feature of Comments after URIs. 

Something like this:
spotify:artist:23fqKkggKUBHNkbKtXEls4 'Kygo

**Comment by leemmcc** [comment]
I actually just put a comment above them like

# Kygo
spotify:artist:23fqKkggKUBHNkbKtXEls4

Seems to work fine, not sure if it processes and fails, or is ignored, but
I haven't had an issue with it.

**Comment by rygos** [comment]
Looks interesting, i will give it a try =)

**Comment by jrnewell** [comment]
I added "same line" comments to ``2.10.7``
```
spotify:artist:23fqKkggKUBHNkbKtXEls4 #Kygo
```
