### ISSUE TITLE
'Total' progress doesn't reflect skipped files

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#29]
The new 'total' progress indication is very useful, but it doesn't seem to reflect skipped files. When I run the ripper on a text file with a list of items, let it rip a few tracks, and then run it again on the same file (having it skip existing files), the total remains the same, and the progress starts from 0:00. Should this be incremented by the length of each skipped file when it is skipped?

**Comment by dylanjboyd** [comment]
Alternatively, it may make more sense if the total time of tracks to be ripped is reduced by the accumulative length of tracks skipped.

**Comment by jrnewell** [comment]
OK.  I accounted for skipped files in the total progress duration.  The fix is in ``1.2.5``.
