### ISSUE TITLE
"spotify-ripper: error: too few arguments"

### ISSUE THREAD

**Issue by beboeverbebo** [jrnewell/spotify-ripper#32]
every time i execute spotify-ripper this comes out at the end "spotify-ripper: error: too few arguments"

e.g.: MacBook-Pro-de-Eric:~ worldwarhack$ spotify-ripper
        usage: spotify-ripper [-h] [-S SETTINGS] [-a] [-A] [-b {160,320,96}] [-c]
                      [-d DIRECTORY] [-f] [-F] [-g {artist,album}] [-k KEY]
                      [-u USER] [-p PASSWORD] [-l] [-L LOG] [-m] [-o] [-s]
                      [-v VBR] [-V] [-r]
                      uri [uri ...]
       spotify-ripper: error: too few arguments

**Comment by jrnewell** [comment]
I am confused. Are giving it a Spotify URI?  I don't see it in your example.

**Comment by beboeverbebo** [comment]
Yeah, sorry I should have been more specific when I first run Spotify-ripper to show me the main menu I get that phrase at the end of the menu. 

This one to be clear. 
"spotify-ripper: error: too few arguments"

**Comment by jrnewell** [comment]
ok.  If you want to see the help menu without that error message just do: 

```spotify-ripper -h```

or

```spotify-ripper --help```

**Comment by beboeverbebo** [comment]
thank you, 
Now i'm getting a "no credentials" error, when i try to rip a track.

![captura de ecra 2015-05-29 as 18 14 53](https://cloud.githubusercontent.com/assets/12373549/7888275/29a539b8-062f-11e5-9a64-21e4b0ff7a7b.png)

**Comment by jrnewell** [comment]
Hmm... that might be a bug.  In the mean time, just not include the -p option and it will ask you for password interactively.

**Comment by beboeverbebo** [comment]
it doesn't ask me for my password nor it does for the username ,if i leave out of the command it just keeps given me "no credentials stored" error

**Comment by jrnewell** [comment]
Sorry, you caught me right when I was going on vacation.  I just tried it on my machine (OS X - Yosemite) and didn't experience the same issue.  Do you have a -l somewhere in your username, can you try putting your user name in quotes?
```
spotify-ripper -u "my-user-name"
```

Which version of python are you using?

**Comment by darkkase** [comment]
same issues   "no credentials stored" 
so i delete config.ini  and works

**Comment by jrnewell** [comment]
do you remember what was in your config.ini?

**Comment by beboeverbebo** [comment]
sorry for taking so long just so it today ,i am using ver 2.7

**Comment by darkkase** [comment]
yes... 

[main]
ascii = True
bitrate = 320
flat = True
last = True
remove_from_playlist = False


in other topics.

i try  run  with tsocks  and dont work because in my work  spotify is banned   :3

**Comment by beboeverbebo** [comment]
Something else has me puzzled,
when i try to rip uris through a list as soon i select a track it logs me out.


![captura de ecra 2015-06-12 as 22 09 29](https://cloud.githubusercontent.com/assets/12373549/8140027/24c5a168-1150-11e5-8770-5b40c4d6041f.png)

**Comment by jrnewell** [comment]
@arkkase: the entry ``last = True`` will cause this issue if you haven't logged in yet.  It tells spotify-ripper to try to login using the last previous successful login.  Once you logged in once, that ``config.ini`` file should work fine.

@beboeverbebo: I know it is a little confusing, but the file ``list_of_uris.txt`` should be in the same directory where you are running the script and not in ``~/.spotify-ripper``.

**Comment by beboeverbebo** [comment]
thanks for the feedback ,
got to work without more problems :)
