### ISSUE TITLE
Providing artist URI retrieves "appears on" albums

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#36]
When ripping an artist from Spotify, the albums under the "Appears on" section are also retrieved. Would it be possible to control this via a command line switch or other configuration?

**Comment by jrnewell** [comment]
Do you have an example artist I can test with and which tracks should be excluded when enabled?  It looks like this option is available via the web api but not libspotify (which is no longer being developed).

**Comment by dylanjboyd** [comment]
Late Night Alumni `spotify:artist:6JtFllJR7nhh8fa6oGefSj` seems to bring in:
- Super Trance `spotify:album:3PNXKncjJbEYnFRMMsJwNp`
- Amsterdam Dance Event 2014: Black Hole Recordings `spotify:album:324BCIAloO6p3yimj0ZFti`
- Why Ask Why (Digital Lab & Mits Remix) `spotify:album:65HNhsknzTkLlUJ7M2Hu5K`.

I presume the remaining albums found under "APPEARS ON" in the Spotify app would also be downloaded, but I haven't tested that.

**Comment by jrnewell** [comment]
OK, the web api allows these options types for ``GET https://api.spotify.com/v1/artists/{id}/albums``:

* album
* single
* appears_on
* compilation

I added the option ``-x | --exclude-appears-on``  to version ``1.4.0`` which retrieves albums via the web api with options ``album_type=album,single,compilation``.  Let me know if that works for you.

**Comment by egeu5** [comment]
I get
spotify-ripper: error: unrecognized arguments: -x
on version 2.9.1 :(

**Comment by lilmike** [comment]
I believe -x was replaced by --artist-album-type=ep,single,album,compilation or similar.
-Michael
