### ISSUE TITLE
Song rips to filename showing character code

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#37]
The song "Don't Make Me Wait"
`spotify:track:4PHB3zQfrRXuHNfKKQSkzq`

rips to the following filename:
`LeToya Luckett - Don?\#200\#231t Make Me Wait (feat. T.I.).mp3`

Is this correct?

**Comment by jrnewell** [comment]
Do you have the ``-a | --ascii`` or ``-A | --ascii-path-only`` option set (either as argument or via config file)?

**Comment by dylanjboyd** [comment]
No, I don't. Would this solve the issue?

**Comment by jrnewell** [comment]
well I would expect to see something like that with those options set - it tells the script to encode the file name from Unicode -> ASCII which is what it looks like it is doing here.

Which options do you have set when you run spotify-ripper?  Which platform are you using?  I just tried that track on OS X Yosemite and didn't see this issue.

**Comment by jrnewell** [comment]
Actually this might be related to your terminal not showing unicode characters...  what happens if you run this on the command line, do you see a checkmark and Cyrillic characters?
```
python -c "print u'\u2713'"
python -c "print u'\u0420\u043e\u0441\u0441\u0438\u044f'"
```
Output:
```
✓
Россия
```

**Comment by dylanjboyd** [comment]
I do see those characters, yes. The machine that this occurred on was Ubuntu 14.04 running `tmux`, but I couldn't reproduce the error using the commands you provided in that scenario, nor on my local machine.

**Comment by jrnewell** [comment]
If you rip that track without tmux running do you see the same filename issue?

**Comment by dylanjboyd** [comment]
With *spotify-ripper 1.4.0*, this doesn't happen using any of the following environments:
- Mac OS X 10.10.3
- Ubuntu Server 14.04
- Ubuntu Server 14.04 *with tmux*
