### ISSUE TITLE
Unsure about the config file

### ISSUE THREAD

**Issue by Froztiez** [jrnewell/spotify-ripper#39]
I can't for the love of me figure out how to use the config file. I've tried all kinds of arguments, but I can't figure out how to do it, sorry if I'm a noob, I'm fairly new at this python thing, ubuntu even. The included .ini files is called default_config.ini, but in the readme it says it's called config.ini, do I need to rename to that?

**Comment by jrnewell** [comment]
The config file is just a convenience tool so you don't have to keep typing the same options each time you run the script, so it should still work without it.  However, in general this should work:

* Download the ``default_config.ini`` file
```
cd ~/Download
wget https://raw.githubusercontent.com/jrnewell/spotify-ripper/master/default_config.ini
```

* Copy the the ``default_config.ini`` file to the directory ``~/.spotify-ripper`` 
```
cp default_config.ini ~/.spotify-ripper/
```

* Rename the file to ``config.ini``
```
cd ~/.spotify-ripper
mv default_config.ini config.ini
```

* Open the ``config.ini`` file and remove options you don't want set by default and edit ones you want to be different, then save (for example, I set ``last = True`` so you don't need to pass the ``-l`` or ``-u`` option)
```
gedit config.ini
```

That should be all there is to it!

As an example, this what I use for my ``config.ini`` file (mainly for testing purposes)
```ini
[main]
last = True
overwrite = True
```

**Comment by Froztiez** [comment]
Alright, thanks, but I am unsure whether or not I need to type an option like -S or it uses the config file on it's own, but without typing anything, it doesn't seem to do anything.

**Comment by jrnewell** [comment]
I am glad that you got it working.  The ``-S`` option is only if you want to have your config and temp files in a location different than the default one (``~/.spotify-ripper``)
