### ISSUE TITLE
Show current download speed

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#41]
It would be useful if the download speed is shown for the current download. This could look similar to the following.
```
Loading track...
[ 349 / 481 ] Ripping spotify:track:3lzMmk9e8kgotG1CAAIHJl
/Users/user/Downloads/spotify/focus/James Newton Howard/Lady In The Water/James Newton Howard - The Healing.mp3
Track Download Size: 9.31 MB
Progress: [=====================================   ] 03:50 / 04:04        (~00m 15s remaining)
Total:    [======================                  ] 11:48:07 / 21:02:29        (~06h 12m remaining)
Speed:    [=======================                 ] 165 kB/s        (max. 286 kB/s)
```
In the above scenario, the scale of the bar changes depending on the maximum speed reached.

In a simpler scenario, the speed could simply be shown below the total instead of a bar representing speed relative to historical values.

**Comment by wolkenschieber** [comment]
Ripping is done in real time. Showing the speed makes no sense.

**Comment by dylanjboyd** [comment]
From what I've seen, it's closer to 2x real-time, but you have a point in the sense that it rarely deviates. I didn't think this one through!
