### ISSUE TITLE
FLAC, AAC or Opus usable?

### ISSUE THREAD

**Issue by Tr4sHCr4fT** [jrnewell/spotify-ripper#42]
can the script be adapted to using libflac, libfdk_aac or libopus for encoding?

Spotiy Premium uses ogg 320kbit for streaming which can be considered nearly transparent
ripping that to MP3, even at 320kbit, will impact a noticeable loss in quality
and you waste space by using an old legacy codec over a modern efficient one,
which can achieve almost transparent archive quality at only 256 kbit vs 320

**Comment by jrnewell** [comment]
I can look into this.  I will probably just stream in through the command line tool like I do for lame instead of trying to wrap the library.  It doesn't look too difficult for FLAC since there is a CLI tool readily available and mutagen can add metadata to it.  I didn't really see much for fdk_acc other than this https://github.com/nu774/fdkaac.

**Comment by Tr4sHCr4fT** [comment]
that would be awesome!
FLAC output with metatada would be even sufficient to start with
it will need two passes but one can effectively transcode to whatever needed without midway quality loss

**Comment by jrnewell** [comment]
OK.  I added FLAC support in version ``1.5.0`` using the ``--flac`` option.  I might look into making an ogg and opus option too.

**Comment by jrnewell** [comment]
Btw.. I left the FLAC compression level on default.  I was thinking about changing it to 'best' since the stream is not exceptionally fast, so compression time shouldn't be an issue.  What do you think?

**Comment by Tr4sHCr4fT** [comment]
yeah, go for it!
i just tested it in my Ubuntu 14.04 VM on a 2005'ish Pentium M 2.16 and still used only ~30% CPU

i'm very happy with the results. good quality, album cover working. great job! :)

compared the output with Spek and the FLAC has clearly more information
also attached analysis of the retail/CD reference (but track is longer)

![david guetta - bad feat vassy - radio edit mp3](https://cloud.githubusercontent.com/assets/1455397/8171190/6ccf0572-13b6-11e5-8983-95511c159cdc.png)
![david guetta - bad feat vassy cd flac](https://cloud.githubusercontent.com/assets/1455397/8171188/6cc8952a-13b6-11e5-8786-67f665075cad.png)
![david guetta - bad feat vassy - radio edit flac](https://cloud.githubusercontent.com/assets/1455397/8171189/6ccd9638-13b6-11e5-9a82-0a58ddd3b198.png)

strangely, the MP3 ist always shown with ~250k but file info says 320k, even set to CBR
and i can not play/open the pcm file dumped with --pcm switch ... is it even supposed to?

**Comment by VikasRana** [comment]
I still don't get it. Spotify streams at 320 OGG and here we are using a codec to convert file to lossless? Isn't that called a transcode? Or am i missing something? I need help here.

**Comment by Tr4sHCr4fT** [comment]
Spotify uses a proprietary implementation of OGG with added Encryption. so this script actually "plays" a track near-realtime via the official library, but pipes the raw output to an encoder instead of your sound card. FLAC can be used to store this data exactly avoiding another quality degrading transcoding pass, or as midway container for later manual conversion,  but of course you will not actually get back the data of the master.

**Comment by VikasRana** [comment]
Ok got it now. I tried downloading a track in FLAC and here is it's properties. Is it possible to download in it's full size with compressing anything. See this image:

<img>http://s14.postimg.org/jrukg25ht/screenshot_770.png</img>

As you can see the FLAC size is around 9 Mb but I want to download that as 15Mb track.

**Comment by Tr4sHCr4fT** [comment]
you could pass it to flac for decode and pipe to flac for encode with added
-0 arg, but why you would want that?
compression is losless and saves space without cons
Am 21.06.2015 15:07 schrieb "VikasRana" <notifications@github.com>:

**Comment by Tr4sHCr4fT** [comment]
i've added selectable flac compression level to my branch

**Comment by Tr4sHCr4fT** [comment]
wav option added
