### ISSUE TITLE
Is there any way to speed up track download?

### ISSUE THREAD

**Issue by TobyMellor** [jrnewell/spotify-ripper#44]
Hi,
I noticed the tracks are currently downloading at the speed of <trackduration>/1.5.
Is there any way to increase this? If so, how? If not, why not? Could you give me some insight as to how the plugin works and why the limit is in place?
Thanks.

**Comment by jrnewell** [comment]
I don't think so - at least not very easily.  The script uses libspotify which is provided by Spotify for streaming music to a third-party music player (like Mopidy) but not for downloading.  Libspotify will send chunks of music data to the script and then wait for the script to say it is done playing or processing the data before sending the next chunk.  Therefore, I am limited by how fast that process is.

It is possible that the libspotify is caching data before it is passing it to the script - I haven't really investigated it.  One could theoretically try to reverse engineer what it is doing and try to make it download faster, but I am sure that would be a quick way to get banned from Spotify.

**Comment by jrnewell** [comment]
This is relevent callback from libspotify that does what I am describing
```python
def on_music_delivery(self, session, audio_format, frame_bytes, num_frames):
    self.rip(session, audio_format, frame_bytes, num_frames)
    return num_frames
```

**Comment by TobyMellor** [comment]
Okay thanks for the information. The plugin works great as it is, but would be even greater if it was faster.
Thanks again.
