### ISSUE TITLE
update with no '--mp4' option

### ISSUE THREAD

**Issue by beboeverbebo** [jrnewell/spotify-ripper#48]
I recently updated spotify-ripper to add the new '--mp4' feature ,but it doesn't seem to have such a option

![captura de ecra 2015-06-20 as 18 04 31](https://cloud.githubusercontent.com/assets/12373549/8268279/f584b85c-1777-11e5-84a5-9c3c1d654236.png)

, there is something else when i tried to install 'fdkacc' the following error came up

![captura de ecra 2015-06-20 as 18 11 03](https://cloud.githubusercontent.com/assets/12373549/8268283/0adb0a9e-1778-11e5-9838-66f495b51386.png)

**Comment by Tr4sHCr4fT** [comment]
v2.0.0 seems been pushed to pypi repo yet,
you have to git clone it and then run setup.py

fdk-aac must be compiled yourself from source

**Comment by jrnewell** [comment]
Yeah sorry, ``2.0.0`` should be up now.

**Comment by jrnewell** [comment]
Also, i am trying to put in a ``fdkaac`` formula into homebrew, but it is not there yet.  For now you need to compile it manually like @Tr4sHCr4fT said.

**Comment by Tr4sHCr4fT** [comment]
https://launchpad.net/~mc3man/+archive/ubuntu/fdkaac-encoder

at least for Ubuntu there seems to be a repo with the binaries

**Comment by jrnewell** [comment]
Yeah that will probably work although it is slightly out of date.  Sometimes I find setting up a ppa more trouble than it is worth :)
