### ISSUE TITLE
Album with Various Artists (VA) gets saved in many folders.

### ISSUE THREAD

**Issue by VikasRana** [jrnewell/spotify-ripper#49]
Generally default is artist/album/artist - song.mp3 and if album is ripped which contains many artists this leads to saving the songs in the directory of their respective artist, thus a single album gets saved in many folder. If -f or -F is used it works fine, but if two Various Artists (VA) albums are downloaded using -f or -F it mixes up the song of the two in the single directory.

I guess album/artist - song.mp3 as a Default should be fine for all categories of albums in spotify.

Example of VA album:: spotify:album:01Q4WKM4cQFX6Vl1IGSzrY

**Comment by jrnewell** [comment]
I think I am going to look into allowing the user defined their own output format because everyone seems to have their own opinion on this.

In the mean time I look into see if I can detect a VA albums and put it into a VA directory.

**Comment by VikasRana** [comment]
Thanks a lot. You people are doing great here. Keep it up!

**Comment by jrnewell** [comment]
Ok, I think version ``2.0.2`` should solve your immediate issue.  I made a change to if you pass in album URI, it will use the album artist ("Various Artists") instead of the track artist in the path.

**Comment by VikasRana** [comment]
Getting this when I'm upgrading it..

root@vps6917:~# pip install --upgrade spotify-ripper
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by jrnewell** [comment]
Should it just join the names if there are multiple artists?

**Comment by VikasRana** [comment]
I believe that will be helpful in this case. Thanks again for all your work, and apologies for the late reply.

**Comment by jrnewell** [comment]
OK.  You can do this now in version ``2.2.1`` using the ``{album_artists_web}`` format string variable.  It needs to hit the Spotify Web API to get all the artists for an album.
