### ISSUE TITLE
Can't login with Facebook

### ISSUE THREAD

**Issue by ajthemacboy** [jrnewell/spotify-ripper#52]
Hi, I can't login with Facebook. I'm using my Facebook login credentials. Am I doing something wrong? It says "Encountered issue while logging into Spotify, aborting..."

**Comment by jrnewell** [comment]
Does it say an error message before that?  Can you post your full log (sans any private info).

**Comment by ajthemacboy** [comment]
I just figured it out. I had to use the numerical username and set a device password in my profile. Thanks! 

I am however having another issue. Since spotify no longer supports URI links, I have to send my self an open.spotify.com link and use http://iwantmyspotifyuri.com to convert it to a URI. However, when I use the URI I get (spotify:user:1244053549:playlist:1R8fjBgzxN37XREQVNjcfh) it shows a list of songs containing "Uri". How do I download my main song playlist?

**Comment by ajthemacboy** [comment]
Nevermind, I got it - I was using both 'uri' and my actual uri. Thanks!

**Comment by jrnewell** [comment]
I don't understand what you are saying by "it shows a list of songs containing 'Uri'"

You should just be able to do this to download your playlist:
```
spotify-ripper -l spotify:user:1244053549:playlist:1R8fjBgzxN37XREQVNjcfh
```

Also if you are using the desktop app, you can right-click on your playlist on the side-menu and it gives you an option to copy the uri.
