### ISSUE TITLE
PEP-8

### ISSUE THREAD

**Issue by fratellolupo** [jrnewell/spotify-ripper#56]
Not to be nitpicking here, but would you consider stricter conformance to PEP-8 coding conventions?

In particular:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length
https://www.python.org/dev/peps/pep-0008/#imports

My code editor enforces some of these rules when saving (bringing unnecessary changes to your code), or displays distracting warnings for others.

I could send a pull request, although I am unsure if it would help? Your editor probably has settings to enforce these, should you chose to....

Of course, I would understand if it did not suit your workflow...

**Comment by jrnewell** [comment]
I am just using sublime so it doesn't really enforce much :smile:   I will try doing a PEP8 reformatting in PyCharm to see if that helps.

**Comment by fratellolupo** [comment]
We seem to have this for Sublime:
https://bitbucket.org/StephaneBunel/pythonpep8autoformat
I would not know; your call...

**Comment by jrnewell** [comment]
The codebase in ``master`` is now more PEP8 compliant.
