### ISSUE TITLE
search for tracks issue - TypeError: 'Track' object is not iterable

### ISSUE THREAD

**Issue by n0012** [jrnewell/spotify-ripper#6]
./ripper.py -l -b 320 "artist:'A Tribe Called Quest' album:'The Low End Theory'"

Logging in...
INFO:spotify.session:Spotify logged in
Searching for query: artist:'A Tribe Called Quest' album:'The Low End Theory'
Results
  1 [The Low End Theory] A Tribe Called Quest - Buggin' Out (57)
  2 [The Low End Theory] A Tribe Called Quest - Jazz (We've Got) (56)
  3 [The Low End Theory] A Tribe Called Quest - Check the Rhime (54)
  4 [The Low End Theory] A Tribe Called Quest - Scenario - LP Mix (52)
  5 [The Low End Theory] A Tribe Called Quest - Excursions (52)
  6 [The Low End Theory] A Tribe Called Quest - Butter (48)
  7 [The Low End Theory] A Tribe Called Quest - Vibes and Stuff (47)
  8 [The Low End Theory] A Tribe Called Quest - Verses from the Abstract (47)
  9 [The Low End Theory] A Tribe Called Quest - Rap Promoter (45)
  10 [The Low End Theory] A Tribe Called Quest - Show Business (45)
  11 [The Low End Theory] A Tribe Called Quest - What? (43)
  12 [The Low End Theory] A Tribe Called Quest - Infamous Date Rape (43)
  13 [The Low End Theory] A Tribe Called Quest - Everything Is Fair (43)
  14 [The Low End Theory] A Tribe Called Quest - Skypager (42)

Pick track(s) (ex 1-3,5): 1-14

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "./ripper.py", line 107, in run
    for idx,track in tracks:
TypeError: 'Track' object is not iterable

**Comment by jrnewell** [comment]
Fixed regression from commit 96b91b6 in commit b87ebb9
