### ISSUE TITLE
new format parameter not working as intended.

### ISSUE THREAD

**Issue by tinstep** [jrnewell/spotify-ripper#61]
I name my albums starting with a Year like this

Carl Orff/(1912) - Carmina/01 - track name

however, when i choose the following naming standard, 
Format= {album_artist}/({Year}) -  {album}/{track_num} - {track_name}.{ext}
i get this,
Carl Orff/({Year}) - Carmina/01 Track Name

it dosnt resolve the Year as it is in brackets.

**Comment by jrnewell** [comment]
The variable names are case-sensitive and all lower case, so you actually need to write it as ``{year}``.  I will look to see if can make this more flexible.

**Comment by tinstep** [comment]
yip, user error, sorry 'bout that - it works perfectly, please close.
