### ISSUE TITLE
Add ability to pad track number in format string

### ISSUE THREAD

**Issue by tinstep** [jrnewell/spotify-ripper#67]
(Enhancement)

Hi,
Currently, when using the format string for the {track_number} the first track (for instance) gets:
1 - tracktitle.mp3

but then if i have a track 11, they get sorted together in my file manager.

if we could have a {track_number_padded}, so it would look like
01 - tracktitle.mp3
02 - tracktitle.mp3
...
11 - tracktitle.mp3

that would be awesome

**Comment by jrnewell** [comment]
Added this functionality to version ``2.2.0``.  You can now specify a zero-filled padding length in the format string: for example, ``{track_num:2}`` produces your example.  This works for these options:  ``{idx}``, ``{track_num}``, and ``{disc_num}``

**Comment by tinstep** [comment]
Works perfectly, thanks !

Please close
