### ISSUE TITLE
tracks not available

### ISSUE THREAD

**Issue by marianolatorre** [jrnewell/spotify-ripper#68]
Would it be possible to output a file with the list of all unavailable tracks? I'm using spotify-ripper to backup the list of my favourite songs which I started years ago and as expected many tracks have become unavailable because of artists pulling out their songs. At the moment it's printing "Track is not available, skipping..." 

Maybe append the track name and artists in a single line to a file unavailable-tracks.txt or something very simple, so that even if the process is stop, later on I can try to download those tracks from a different source or add them on spotify if they where already re uploaded by the artist as a new track but same song.

I could try this on a separated branch, sounds like a quick one... but first what do you guys think?

**Comment by jrnewell** [comment]
Makes sense to me.  Sticking with the having an option for everything design this has, I would add an option that takes a filename and appends the track URI to that file when it is not available.

**Comment by jrnewell** [comment]
I just went ahead and implemented it.  It is in version ``2.2.2``.  The new option is ``--fail-log``.

**Comment by marianolatorre** [comment]
wow that's great, many thanks!

I wonder if it's still possible to get the original song and artist name from an unavailble song URI? I mean to be able to then download it from somewhere else :)

**Comment by jrnewell** [comment]
It gives a song and artist name summary of the failed tracks at the end. I also made a short script for you that will give you the names using the Web API.  Just pass it the file as an argument.


https://gist.github.com/jrnewell/3ab6495896b4f0538543

**Comment by marianolatorre** [comment]
awesome! thanks
