### ISSUE TITLE
Running in a raspberry pi fails due an error

### ISSUE THREAD

**Issue by bitmarker** [jrnewell/spotify-ripper#7]
I've got the script running on a raspberry pi and it seems to work.. partially. The script records the track but fails when closing the file and shows following error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "./ripper.py", line 132, in run
    self.finish_rip(track)
  File "./ripper.py", line 316, in finish_rip
    self.pipe.close()
IOError: close() called during concurrent operation on the same file object.

**Comment by jrnewell** [comment]
Hmm ... I tried it on my Raspberry Pi and I didn't see that error.  Perhaps my SD card is a bit faster so it isn't seeing that race condition.  Can you check if commit 306efd4 fixed it for you?  Can you tell me which query you were using and do you see the error at the end of every file or just once in a while?

**Comment by bitmarker** [comment]
It happens every time. But I’ve fixed it. It’s maybe not the most elegant solution, but it works for me.

I’m closing the pipe like this now:

    def finish_rip(self, track):
        if self.pipe is not None:
            print(Fore.GREEN + 'Rip complete' + Fore.RESET)
            close_attempts = 100
            while close_attempts > 0:
                try:
                    self.pipe.close()
                    close_attempts = 0
                except IOError:
                    if close_attempts > 0:
                        close_attempts = close_attempts - 1
                        continue
                    raise

**Comment by jrnewell** [comment]
I am glad you were able to fix it.   I agree that is kind of a hack - is there anyway you try testing the latest version?  The only other thing I can think of is to add some thread locks around the child process resource.

**Comment by bitmarker** [comment]
Hi! It’s working. Flushing the pipe did the job! Thank you!

**Comment by jrnewell** [comment]
Great!
