### ISSUE TITLE
Add a command line argument for id3 tag comments

### ISSUE THREAD

**Issue by thenktor** [jrnewell/spotify-ripper#72]
Hi,

it would be nice to have a command line argument for additional id3 tag comments, so you could set something like this `--comment "Transcoded from Spotify Vorbis 320kbps"`. This way at least it is possible to identify transcoded files.

**Comment by VikasRana** [comment]
+1 for this.

**Comment by jrnewell** [comment]
Added to version ``2.2.5``.
