### ISSUE TITLE
Playlist handling

### ISSUE THREAD

**Issue by wolkenschieber** [jrnewell/spotify-ripper#73]
Hi,

I'm on spotify for the playlists. I also want the filename to by numbered by their position in the list, so that the mp3-player (<- hardware device) will play it in the correct order.
For this special handling is forked this project and implemented some library handling, which synchronizes playlists and keeps the files and their order up to date. The corresponding pull request was never merged, so I'm wondering how do you guys handle playlists? Is there a way I'm not aware of in the current version?

Regards
keibak

**Comment by VikasRana** [comment]
If I am not wrongly assuming what you trying to say here then, I think --flat or --flat-with-index might do the job you are seeking.

**Comment by wolkenschieber** [comment]
Yes, but these options won't keep track of changes in the playlist. Eg if the position of a song is changed, it would be downloaded anew instead of just being renamed.

Basically I added some library handling. At first the files in the targetdirectory are iterated and stored. Then the playlist entries are matched against the stored ones. New entries get downloaded, existing will stay. In a final step the files are ordered according to the playlist. Files removed from the playlist will be stored in an attic folder.

**Comment by jrnewell** [comment]
I feel like this feature might be out of the scope for this tool - since the purpose is just to rip the files not really manage a music library.  IMO, it would be awesome if there was a separate tool that could provide this functionality (renaming/moving of the files to sync with your playlist) and interact with spotify-ripper to download the files that are missing.

**Comment by wolkenschieber** [comment]
Well, it wouldn't be too elaborate to implement. The functionality was in this [Pull request](https://github.com/jrnewell/spotify-ripper/pull/19).
But you are right. With a library feature, it would be hard to draw a line between the song recording and the library maintaining.
