### ISSUE TITLE
[ADD FEATURE REQ] Playlist file (.m3u) and Cover Art

### ISSUE THREAD

**Issue by VikasRana** [jrnewell/spotify-ripper#74]
Is it possible to have a feature in which Spotify-ripper automatically extracts cover art and saves in the album folder. And also a feature in which it generates the playlist file of music.

**Comment by jrnewell** [comment]
You can save cover art as a separate file using the new option ``--cover-file`` in version ``2.2.6``.

**Comment by VikasRana** [comment]
Awesome feature.

**Comment by jrnewell** [comment]
Btw... to create an m3u file from the command line (you can put in in a script or bash function for convenience) is
```
find . -name "*.mp3" -o -name "*.m4a" (whatever extensions you want) > playlist.m3u
```
