### ISSUE TITLE
fdkaac brew package now renamed

### ISSUE THREAD

**Issue by ianwinter** [jrnewell/spotify-ripper#75]
The brew package `fdkaac` is now called `fdk-aac` so the dependency check fails.

```Missing dependency 'fdkaac'.  Please install and add to path...
...try brew install fdkaac```

**Comment by jrnewell** [comment]
The naming is a little confusing but fdkaac is the name of the encoder binary and fdk-aac is the name of the library.  Homebrew doesn't have a formula for fdkaac yet - still waiting to me merged (and it will likely have a different name like ``fdk-aac-encoder``.  You need to build it manually for now.

**Comment by ianwinter** [comment]
Thanks for the pointer. I manually just copied the formula from the unmerged branch, also had to switch from python 3.4.3 back to 2.7.10 and all good. Happy to either leave this issue open or you can close it, don't mind.
