### ISSUE TITLE
YEAR-Information not safed in id3-Tag

### ISSUE THREAD

**Issue by karschti** [jrnewell/spotify-ripper#77]
My config.ini:
quality 	= 320
vbr		= 2
format 	= '{artist} - {track_name}.{ext}'

Rip-Information:
Rip complete
xxx - xxx.mp3	[ 5.36 MB ]
-------------------------------------------------------------------------------
Setting artist: xxx
Setting album: xxx
Setting title: xxx
Setting track info: (1, 16)
Setting disc info: (1, 1)
Setting release year: 2011
Adding cover image
Time: 03:58	MPEG1, Layer III	[ ~188 kb/s @ 44100 Hz - Joint Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4: 7 frames
Writing ID3 version v2.4

But the year was not safed in id3-Tag

**Comment by jrnewell** [comment]
What is the Spotify URI of this track?  Are you having this issue with all tracks or just this one?

**Comment by karschti** [comment]
that is with all tracks so

**Comment by jrnewell** [comment]
OK I think I know what is wrong.  I am using the ``TDRL`` tag and I should be using the ``TDRC`` tag.

**Comment by jrnewell** [comment]
OK.  Fixed in version ``2.2.7``.

**Comment by karschti** [comment]
Okay. Very good!
