### ISSUE TITLE
{playlist} format variable does not work

### ISSUE THREAD

**Issue by jotaCede** [jrnewell/spotify-ripper#78]
When saving a playlist, variables {playlist} and {playlist_name} are not replaced by actual playlist name.

In the following example, first track is saved in this file:
/home/myUser/.spotify-ripper/{playlist} - 000 - Pharrell Williams - Freedom.mp3

My config.ini file:

[main]
ascii = True
format = {playlist} - {idx:3} - {artist} - {track_name}.{ext}
bitrate = 160

$ spotify-ripper --user myUser spotify:user:spotify:playlist:5FJXhjdILmRA2z5bvz4nzf
Spotify Ripper - v2.2.6
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	ASCII only
  Output directory:	/home/myUser/.spotify-ripper
  Settings directory:	/home/myUser/.spotify-ripper
  Format String:	{playlist} - {idx:3} - {artist} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Password: 
Logged in as myUser
Loading playlist...
Total Download Size: 384.94 MB
Loading track...
[ 1 / 51 ] Ripping spotify:track:6RB9YvNyP0RZfCUcMtZELH
/home/myUser/.spotify-ripper/{playlist} - 000 - Pharrell Williams - Freedom.mp3
Track Download Size: 6.18 MB
Progress: [=                                       ] 00:05 / 02:42
Total:    [                                        ] 00:05 / 02:48:11

Thanks.

**Comment by karschti** [comment]
The same with me

**Comment by jrnewell** [comment]
That is weird, I don't see it... what platform and python version are you using?

```
$ spotify-ripper spotify:user:spotify:playlist:5FJXhjdILmRA2z5bvz4nzf
Spotify Ripper - v2.2.7
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	ASCII only
  Output directory:	/Users/james/Downloads/Spotify
  Settings directory:	/Users/james/.spotify-ripper
  Format String:	{playlist} - {idx:3} - {artist} - {track_name}.{ext}
  Overwrite files:	Yes
Logging in...
Loading playlist...
Total Download Size: 408.33 MB
Loading track...
[ 1 / 51 ] Ripping spotify:track:6RB9YvNyP0RZfCUcMtZELH
/Users/james/Downloads/Spotify/Today's Top Hits - 000 - Pharrell Williams - Freedom.mp3
Track Download Size: 6.18 MB
Progress: [======                                  ] 00:28 / 02:42        (~01m 35s remaining)
Total:    [                                        ] 00:28 / 02:58:24        (~02h 02m remaining)^C
Aborting...
Deleting partially ripped file
Logging out...
```

**Comment by jotaCede** [comment]
$ python -V
Python 2.7.6

$ uname -or
3.13.0-37-generic GNU/Linux

$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"

NOTE: If this could help, I installed python-dev but not pyenv. So, during install, "pyenv rehash" command failed, but spotify-ripper seems to work.

Thanks!

**Comment by karschti** [comment]
I found the mistake:

is

Unicode support: ASCII only

turned off,

{} not working playlist

**Comment by karschti** [comment]
In Spotify Ripper - v2.2.6 hatte es bei mir nicht funktioniert. Nun in Spotify Ripper - v2.2.7 geht es.

**Comment by jrnewell** [comment]
Sehr Gut!

@jotaCede does it work for you if you upgrade to 2.2.7?
```
sudo pip install --upgrade spotify-ripper
```

**Comment by jotaCede** [comment]
Just upgraded to last version (2.2.8). Works perfect now :)

Thanks!
