### ISSUE TITLE
Encountered issue while logging into Spotify, aborting...

### ISSUE THREAD

**Issue by jbakker81** [jrnewell/spotify-ripper#79]
Just created a premium account and downloaded the binary key, wich i put in ~/.spotify-ripper. Also tried using the -K argument. What am i doing wrong? 

mprotect(0x7fb9cbb7d000, 4096, PROT_NONE) = 0
clone(child_stack=0x7fb9cc37cff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb9cc37d9d0, tls=0x7fb9cc37d700, child_tidptr=0x7fb9cc37d9d0) = 17142
futex(0x7fb9d316bd44, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fb9d316bd40, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7fb9d316bd00, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fb9d50f9330, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x7fb9d316bd44, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3, {1437036748, 756048000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb9d316bd00, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb9d316bd40, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fb9d316bd44, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5, {1437036748, 761120000}, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fb9d316bcc4, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fb9d316bcc0, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7fb9d316bc80, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fb9d316bd00, FUTEX_WAKE_PRIVATE, 1) = 1
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb9cb37c000
mprotect(0x7fb9cb37c000, 4096, PROT_NONE) = 0
clone(child_stack=0x7fb9cbb7bff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb9cbb7c9d0, tls=0x7fb9cbb7c700, child_tidptr=0x7fb9cbb7c9d0) = 17143
futex(0x7fb9d316bd44, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fb9d316bd40, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7fb9d316bd00, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fb9d50ac770, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
Logging in...
futex(0x7fb9d316bd44, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 12, {1437036748, 764200000}, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fb9d316bd44, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 14, {1437036748, 764200000}, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fb9d316bd44, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 15, {1437036748, 764200000}, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fb9d316bd00, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb9d316bd40, FUTEX_WAKE_PRIVATE, 1No credentials stored
) = 1
futex(0x7fb9d316bd44, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 17, {1437036748, 764307000}, ffffffffEncountered issue while logging into Spotify, aborting...

**Comment by jrnewell** [comment]
I am not sure why you are seeing all of those debug messages - it looks like you might be using the wrong library architecture or have some debug setting enabled.

However, I see this log message in that mess: "No credentials stored".  You need to login once using the -u option before using the -l option.

**Comment by jbakker81** [comment]
Thats what i am using:

spotify-ripper -u *** -p *** spotify:user:***:playlist:1rC55JwZ6OYsjQFSmILKmO

Spotify Ripper - v2.2.8
  Encoding output:	FLAC, Compression Level: 8
  Spotify bitrate:	320 kbps
  Unicode support:	ASCII only
  Output directory:.spotify-ripper
  Settings directory:	/home/ppine/.spotify-ripper
  Format String:	{artist} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
No credentials stored
Encountered issue while logging into Spotify, aborting...

**Comment by jrnewell** [comment]
Does your username have a dash in it?  Try putting quotes around your user and pass.  Are you using a config.ini file?

**Comment by jbakker81** [comment]
No not dashes in the username, u mentioned the config.ini file wich i indeed had setup before usage. Now when i the command without the ini file its working perfectly! Case closed, and thanks for this great script.

**Comment by jrnewell** [comment]
yeah, you aren't the first person who had that issue.  I will put something in the README to warn against that.  Thanks!
