### ISSUE TITLE
Not writing Artwork in MP3 files on latest version.

### ISSUE THREAD

**Issue by VikasRana** [jrnewell/spotify-ripper#80]
Please have a look at this new issue.

**Comment by jrnewell** [comment]
Are you embedding the cover art or storing it in a separate file?

**Comment by VikasRana** [comment]
Yes storing it as separate file. Should I not?

**Comment by VikasRana** [comment]
I was storing it as a separate file, now I removed --cover-file and its working again. Thanks for your help. Clossing this issue as it is solved.

**Comment by jrnewell** [comment]
Hey sorry for the slow reply - I am on vacation.  From my understanding each player has a different standard for how they check for external cover art files.  Some of them look for cover.jpg while other cache it in some other directory.  Embedding it in the id3 tags is probably the easiest (but more space is used) :smile:
