### ISSUE TITLE
Still having confusion with Genre.

### ISSUE THREAD

**Issue by VikasRana** [jrnewell/spotify-ripper#81]
If I want to get the genre of few albums altogether, how should I command? Is it like this, -g {artist 1,album 1} -g {artist 2,album 2}.

Also was willing to know, can Genre be made default if S-R extract info from URIs.

**Comment by jrnewell** [comment]
it is either "album" or "artist".  However, Spotify's genre field is pretty sparse - I suggest using something like beets to get better genre information.
