### ISSUE TITLE
When saving playlists, create the playlists for saved songs

### ISSUE THREAD

**Issue by chronossc** [jrnewell/spotify-ripper#85]
Hello, nice job u have done here.

I'm dowloading few stuff but saw that only files are saved, but not playlist is in fact created locally.

Is possible to create the playlist that we download when we are dowloading a playlist or list of playlists?

Thx

**Comment by jrnewell** [comment]
The new option to enable it is ``--playlist-m3u`` and is available in ver ``2.3.2``.
