### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by VikasRana** [jrnewell/spotify-ripper#87]
spotify-ripper -a -f "/root/{album_artist} - {album} [{year}]/{track_num}. {artists} - {track_name}.{ext}" -b 320 -c --flac -u myuser -p mypass spotify:album:6Tm5jVuYBZ9ecq2pECuSnm spotify:album:14RFlfBV7S9OVbj7gk5OuJ
Spotify Ripper - v2.2.8
  Encoding output:      FLAC, Compression Level: 8
  Spotify bitrate:      320 kbps
  Unicode support:      ASCII only
  Output directory:     /root
  Settings directory:   /root/.spotify-ripper
  Format String:        /root/{album_artist} - {album} [{year}]/{track_num}. {artists} - {track_name}.{ext}
  Overwrite files:      No
Segmentation fault

The error also with MP3 and other formats. My hoster said it's something with the program and not anything from server side. They said program is trying to access memory that it is not allowed to.

**Comment by nielsiano** [comment]
I get the exact same error with `2.2.9`

**Comment by jrnewell** [comment]
Do you have the stack traces or anything?  My hunch that this might be due to a memory exception in the encoder programs.

**Comment by VikasRana** [comment]
I dont have any trace sorry. I will put the program to work again and will copy-paste the details.

**Comment by VikasRana** [comment]
Ok, got something. As it won't let me copy, I am uploading the snapshot of command prompt. Please have a look.
![screenshot_855](https://cloud.githubusercontent.com/assets/5049696/9213554/5eca6d9a-40b1-11e5-831f-b1519d26b323.png)

**Comment by jrnewell** [comment]
OK. I added more checks to prevent divides by zero issues in version ``2.3.2``. Hopefully that resolves the particular issue you are showing in that screenshot.
