### ISSUE TITLE
spotify.utils.IntEnum: AttributeError: 'module' object has no attribute 'utils'

### ISSUE THREAD

**Issue by bkk2912** [jrnewell/spotify-ripper#89]
Traceback (most recent call last):
  File "/usr/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.2.9', 'console_scripts', 'spotify-ripper')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/bin/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/usr/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 21, in <module>
    class BitRate(spotify.utils.IntEnum):
AttributeError: 'module' object has no attribute 'utils'

Requirement already up-to-date: spotify-ripper in /usr/lib/python2.7/site-packages
Requirement already up-to-date: pyspotify==2.0.0b4 in /usr/lib/python2.7/site-packages (from spotify-ripper)
Requirement already up-to-date: colorama>=0.3.3 in /usr/lib/python2.7/site-packages (from spotify-ripper)
Requirement already up-to-date: mutagen==1.29 in /usr/lib/python2.7/site-packages (from spotify-ripper)
Requirement already up-to-date: requests>=2.3.0 in /usr/lib/python2.7/site-packages (from spotify-ripper)
Requirement already up-to-date: schedule>=0.3.1 in /usr/lib/python2.7/site-packages (from spotify-ripper)
Requirement already up-to-date: cffi>=0.7 in /usr/lib/python2.7/site-packages (from pyspotify==2.0.0b4->spotify-ripper)
Requirement already up-to-date: pycparser in /usr/lib/python2.7/site-packages (from cffi>=0.7->pyspotify==2.0.0b4->spotify-ripper)

**Comment by jrnewell** [comment]
Hmm... that is a strange.  Do you see that every time?  Can you give me the settings/arguments you are using.  Also, operating system and platform?

**Comment by bkk2912** [comment]
Yes, I see this error every time now.

[main]
user = XXXXXXX
password = XXXXXXX
flat = True
$ spotify-ripper -d /home/X/Music /home/X/Music/list_of_uris.txt

Using Arch Linux with spotify-ripper under the python2 environment.

**Comment by bkk2912** [comment]
pyspotify==2.0.2 update solved the problem :)
