### ISSUE TITLE
Full Stereo encoding in lame instead of normal Stereo.

### ISSUE THREAD

**Issue by VikasRana** [jrnewell/spotify-ripper#91]
I was reading the artice at hydrogenaudio the other day, and found that Full Stereo/Joint Stereo is preferred stereo mode in lame for high bitrate audio. They are considered to be more efficient.

Source: http://www.hydrogenaud.io/forums/index.php?showtopic=30637

Option to select stereo mode in lame might work just perfect. Please consider this.

**Comment by jrnewell** [comment]
Ok, add option ``--stereo-mode`` to set advanced stereo mode for Lame encoder.  It is in ver ``2.3.0``.
