### ISSUE TITLE
Encountered issue while logging into Spotify, aborting...

### ISSUE THREAD

**Issue by syntelman** [jrnewell/spotify-ripper#92]
Hi!
I have a problem with user credentials obviously... (Yes, I have the premoium service and have downloaded the API key). But whenever I try spotify-ripper, with --user USERNAME -p PASSWORD or in any other combination the only output I get is:

Spotify Ripper - v2.3.2
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	ASCII only
  Output directory:	/home/X/.spotify-ripper
  Settings directory:	/home/X/.spotify-ripper
  Format String:	{artist} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
No credentials stored
Encountered issue while logging into Spotify, aborting...
Exception in thread SpotifyEventLoop (most likely raised during interpreter shutdown):

Help? :) Cheers!

**Comment by syntelman** [comment]
Hm. Okay, deleting the config.ini makes everything work. :)

**Comment by jrnewell** [comment]
Yeah, you are not the first person for this issue to happen to.  When I get around to it, I will put in a few more checks to look out for this situation to help out newcomers.

**Comment by jrnewell** [comment]
I commented out options in the included default ``config.ini`` so people won't accidentally set ``last=True`` pre-login.  Hopefully this will prevent further issues.
