### ISSUE TITLE
Support for Spotify free account?

### ISSUE THREAD

**Issue by orschiro** [jrnewell/spotify-ripper#94]
Dear @jrnewell,

Thanks for your work on this software! I have a question to which I could not find a direct answer in the README. Does this script, in order to work, require a Spotify Premium account or does it also support the download of a playlist from a Spotify Free account?

Thankfully,

Robert

**Comment by jrnewell** [comment]
Unfortunately, I am fairly certain you need a premium account to create and keep a Spotify App key active, which the script requires to function.  But I have seen promos where you can 3 months of premium for free.

**Comment by orschiro** [comment]
@jrnewell 

Thanks for your response! I have found a working alternative for me which involves converting a Spotify Free Playlist into a YouTube playlist:

http://www.playlistbuddy.com/

Warmly,

Robert

**Comment by jrnewell** [comment]
Your welcome.  I am glad you found a solution for your issue!
